CREATE TABLE [dbo].[zzz_DELETE_Dev661XLSX]
(
[Dev661XLSX] [int] NOT NULL IDENTITY(1, 1),
[LoanNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUID] [uniqueidentifier] NULL,
[LastModified] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[zzz_DELETE_Dev661XLSX] ADD CONSTRAINT [PK__Dev661XL__2F7326FC014A64B6] PRIMARY KEY CLUSTERED  ([Dev661XLSX]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
