CREATE TABLE [emdbuser].[LOANXDB_X_01]
(
[XRefID] [int] NOT NULL,
[InsertBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_loanxdb_x_01_InsertBy] DEFAULT (replace(suser_sname(),'GRCORP\','')),
[InsertDT] [datetime] NOT NULL CONSTRAINT [df_loanxdb_x_01_InsertDT] DEFAULT (getdate()),
[LastUpdateBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_loanxdb_x_01_LastUpdateBy] DEFAULT (replace(suser_sname(),'GRCORP\','')),
[LastUpdateDT] [datetime] NOT NULL CONSTRAINT [df_loanxdb_x_01_LastUpdateDT] DEFAULT (getdate()),
[Revision] [int] NOT NULL CONSTRAINT [df_loanxdb_x_01_Revision] DEFAULT ((0)),
[_CD5_X31] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X32] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X33] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X34] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X35] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X41] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X42] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X43] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X44] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X45] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X46] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X47] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X53] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CD5_X54] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_3] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_4] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_5] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_6] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_7] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_8] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GFE_REV_9] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_CLSNGREGION] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_PIWCHECKED] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_PIWCHECKEDBY] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_PIWCHECKTIME] [datetime] NULL,
[_CX_EXCPAPRVDBY] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCAPRVDTIME] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCDENIEDBY] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCDENIEDTIME] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_1] [datetime] NULL,
[_CX_EXCREQTIME_1] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLNDCDT_1] [int] NULL,
[_CX_EXCLCKPRCE_1] [decimal] (23, 10) NULL,
[_CX_EXCREQCURPRICE_1] [decimal] (23, 10) NULL,
[_CX_EXCREQCMTS_1] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQPRICE_1] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLENDER_1] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_2] [datetime] NULL,
[_CX_EXCREQTIME_2] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLNDCDT_2] [int] NULL,
[_CX_EXCLCKPRCE_2] [decimal] (23, 10) NULL,
[_CX_EXCREQCURPRICE_2] [decimal] (23, 10) NULL,
[_CX_EXCREQCMTS_2] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQPRICE_2] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLENDER_2] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_3] [datetime] NULL,
[_CX_EXCREQTIME_3] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLNDCDT_3] [int] NULL,
[_CX_EXCLCKPRCE_3] [decimal] (23, 10) NULL,
[_CX_EXCREQCURPRICE_3] [decimal] (23, 10) NULL,
[_CX_EXCREQCMTS_3] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQPRICE_3] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLENDER_3] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_4] [datetime] NULL,
[_CX_EXCREQTIME_4] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLNDCDT_4] [int] NULL,
[_CX_EXCLCKPRCE_4] [decimal] (23, 10) NULL,
[_CX_EXCREQCURPRICE_4] [decimal] (23, 10) NULL,
[_CX_EXCREQCMTS_4] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQPRICE_4] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQLENDER_4] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_COTHIRDPTYCOL] [decimal] (23, 10) NULL,
[_CX_SERVICEFEES_2] [decimal] (23, 10) NULL,
[_FANNIESERVICE_X3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_FANNIESERVICE_X4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CASASRN_X31] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CASASRN_X32] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_VIP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_MC_ESCALATION] [datetime] NULL,
[_CX_SHOPPING] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_PA_FOLLOWUP] [datetime] NULL,
[_CX_PA_ISSUED] [datetime] NULL,
[_CX_PA_DOCS] [datetime] NULL,
[_CX_PA_RECEIVED] [datetime] NULL,
[_CX_RATE_CHASER] [decimal] (23, 10) NULL,
[_CX_EPO_DATE] [datetime] NULL,
[_CX_SPOUSE_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_SPOUSE_EMAIL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_COLLATERAL_REVIEW] [datetime] NULL,
[_CX_COLLATERAL_ANTICIPATED] [decimal] (23, 10) NULL,
[_CX_SUPPORT_REVIEW] [datetime] NULL,
[_CX_DOCS_COMPLETE] [datetime] NULL,
[_CX_ANT_VALUE] [decimal] (23, 10) NULL,
[_CX_APPR_FOLLOWUP] [datetime] NULL,
[_CX_MC_FOLLOW_DATE] [datetime] NULL,
[_CX_LC_FOLLOWUP] [datetime] NULL,
[_CX_USPS] [datetime] NULL,
[_CX_TAXCERT_DATE] [datetime] NULL,
[_CX_PAPERLESS_STARTED] [datetime] NULL,
[_CX_DATAVERIFY] [datetime] NULL,
[_CX_APP_SPLIT] [datetime] NULL,
[_CX_CHARGE_DATE] [datetime] NULL,
[_CX_VOE_TYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_VOE_ORDERED] [datetime] NULL,
[_CX_VOE_FOLLOW] [datetime] NULL,
[_CX_CC_VOE_COMPLETE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_CPL_DATE] [datetime] NULL,
[_CX_TITLE_INVOICE] [datetime] NULL,
[_CX_WIRE_IN] [datetime] NULL,
[_CX_TITLE_COM] [datetime] NULL,
[_CX_CONDO_QR] [datetime] NULL,
[_CX_CONDO_QRCD] [datetime] NULL,
[_CX_CONDO_CR] [datetime] NULL,
[_CX_CQ_FOLLOW] [datetime] NULL,
[_CX_MASTER_REQ] [datetime] NULL,
[_CX_MASTER_R] [datetime] NULL,
[_CASASRN_X164] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CASASRN_X33] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_MORNET_X91] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_SessionUserId] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_INCOME_EXP_VALID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_ASSET_EXP_VALID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_CC228_15] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_CC_VOE_DATE] [datetime] NULL,
[_CX_ABC_UWC_APPROVAL] [datetime] NULL,
[_CX_GET_COMMITTED] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GET_COMMITTED_DENIED] [datetime] NULL,
[_CX_GET_COMMITTED_APPROVED] [datetime] NULL,
[_CX_APPRAISAL_WAIVER] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQCMTS_5] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_5] [datetime] NULL,
[_CX_EXCREQTIME_5] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQCMTS_6] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_6] [datetime] NULL,
[_CX_EXCREQTIME_6] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQCMTS_7] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_7] [datetime] NULL,
[_CX_EXCREQTIME_7] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQCMTS_8] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EXCREQDATE_8] [datetime] NULL,
[_CX_EXCREQTIME_8] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create trigger [emdbuser].[tr_loanxdb_x_01_LogLastUpdate] 
on [emdbuser].[LOANXDB_X_01]
after update
as
/* who				when			what
petervandivier		2016-08-09	TRIGGER to log update revisions
*/
begin
	set nocount on;
	
	update emdbuser.loanxdb_x_01 set 
		LastUpdateBy = replace( system_user, 'GRCORP\', '' ),
		LastUpdateDT = getdate(),
		Revision += 1
	from emdbuser.loanxdb_x_01 a
	join inserted b on a.XRefID = b.XRefID;
end;

GO
ALTER TABLE [emdbuser].[LOANXDB_X_01] ADD CONSTRAINT [pk_loanxdb_x_01] PRIMARY KEY CLUSTERED  ([XRefID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
