CREATE TABLE [emdbuser].[LOANXDB_S_02]
(
[XrefId] [int] NOT NULL,
[_VEND_X396] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X396] DEFAULT (N''),
[_CX_PROPSELLER_2] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROPSELLER_2] DEFAULT (N''),
[_CUST60FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST60FV] DEFAULT (N'//'),
[_CX_UWFUNDCONTROL_3] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWFUNDCONTROL_3] DEFAULT (N''),
[_364] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_364] DEFAULT (N''),
[_UWC_NOTCLEARED] [varchar] (4096) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_UWC_NOTCLEARED] DEFAULT (N''),
[_1792] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1792] DEFAULT (N''),
[_MORNET_X67] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_MORNET_X67] DEFAULT (N''),
[_CX_PROGRAMCODE_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROGRAMCODE_2] DEFAULT (N''),
[_CX_FUNDASSOCPROP_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDASSOCPROP_2] DEFAULT (N''),
[_CUST68FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST68FV] DEFAULT (N''),
[_2007] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2007] DEFAULT (N''),
[_98] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_98] DEFAULT (N''),
[_1838] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1838] DEFAULT (N''),
[_371] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_371] DEFAULT (N''),
[_CUST77FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST77FV] DEFAULT (N''),
[_CX_COMPAREESCR_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREESCR_2] DEFAULT (N''),
[_2019] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2019] DEFAULT (N''),
[_2278] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2278] DEFAULT (N''),
[_SYS_X281] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X281] DEFAULT (N''),
[_SYS_X282] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X282] DEFAULT (N''),
[_SYS_X283] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X283] DEFAULT (N''),
[_SYS_X284] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X284] DEFAULT (N''),
[_SYS_X285] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X285] DEFAULT (N''),
[_SYS_X286] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X286] DEFAULT (N''),
[_CX_INSURNOTE3_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSURNOTE3_1] DEFAULT (N''),
[_SYS_X288] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X288] DEFAULT (N''),
[_CUST65FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST65FV] DEFAULT (N''),
[_SYS_X136] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X136] DEFAULT (N''),
[_SYS_X137] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X137] DEFAULT (N''),
[_CX_COMPARELTV_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPARELTV_2] DEFAULT (N''),
[Log_MS_Comments_Funding] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_Comments_Funding] DEFAULT (N''),
[_728] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_728] DEFAULT (N''),
[_1627] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1627] DEFAULT (N''),
[_CX_CLSDOCDELV_1] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSDOCDELV_1] DEFAULT (N''),
[_FR0106] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0106] DEFAULT (N''),
[_FR0206] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0206] DEFAULT (N''),
[_1130] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1130] DEFAULT (N''),
[_CX_FUNDASSOCKEY_2] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDASSOCKEY_2] DEFAULT (N''),
[_CX_AUSRECOMMENDATION_2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_AUSRECOMMENDATION_2] DEFAULT (N''),
[_REGZGFE_X5] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_REGZGFE_X5] DEFAULT (N''),
[_CX_FUNDASSOCINS1_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDASSOCINS1_2] DEFAULT (N''),
[_CX_AUSSOURCE_2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_AUSSOURCE_2] DEFAULT (N''),
[_1787] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1787] DEFAULT (N''),
[_CUST75FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST75FV] DEFAULT (N''),
[_CX_UWRUSH_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWRUSH_1] DEFAULT (N''),
[_CX_REDRAW_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_REDRAW_1] DEFAULT (N''),
[_410] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_410] DEFAULT (N''),
[_SYS_X81] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X81] DEFAULT (N''),
[_VEND_X398] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X398] DEFAULT (N''),
[_471] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_471] DEFAULT (N''),
[_SYS_X149] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X149] DEFAULT (N''),
[_12] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_12] DEFAULT (N''),
[_SYS_X30] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X30] DEFAULT (N''),
[_CX_COMPAREAMORT_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREAMORT_2] DEFAULT (N''),
[_CX_INSURNOTE4_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSURNOTE4_1] DEFAULT (N''),
[_CX_FUNDCHASETYPE_3] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDCHASETYPE_3] DEFAULT (N''),
[_CX_BROKERCODE_1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_BROKERCODE_1] DEFAULT (N''),
[_1959] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1959] DEFAULT (N''),
[_SYS_X35] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X35] DEFAULT (N''),
[_CX_COMPAREPRG_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREPRG_2] DEFAULT (N''),
[_CX_PAIDLOCODE_3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PAIDLOCODE_3] DEFAULT (N''),
[_DU_LP_ID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DU_LP_ID] DEFAULT (N''),
[_2000] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2000] DEFAULT (N''),
[_2003] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2003] DEFAULT (N''),
[_CX_FUNDCHASEPURP_3] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDCHASEPURP_3] DEFAULT (N''),
[_CUST74FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST74FV] DEFAULT (N''),
[_CX_COMPAREOCC_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREOCC_2] DEFAULT (N''),
[_CX_COMPAREPURP_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREPURP_2] DEFAULT (N''),
[Log_MS_Comments_Shipping] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_Comments_Shipping] DEFAULT (N''),
[_2574] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2574] DEFAULT (N''),
[_2626] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2626] DEFAULT (N''),
[_SYS_X275] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X275] DEFAULT (N''),
[_SYS_X276] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X276] DEFAULT (N''),
[_SYS_X277] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X277] DEFAULT (N''),
[_SYS_X278] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X278] DEFAULT (N''),
[_CUST62FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST62FV] DEFAULT (N''),
[_LIC_GU] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LIC_GU] DEFAULT (N''),
[_SYS_X32] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X32] DEFAULT (N''),
[_1782] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1782] DEFAULT (N''),
[_362] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_362] DEFAULT (N''),
[_CX_ISEXPIRED_2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ISEXPIRED_2] DEFAULT (N''),
[_FR0107] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0107] DEFAULT (N''),
[_SYS_X80] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X80] DEFAULT (N''),
[_SYS_X66] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X66] DEFAULT (N''),
[_18] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_18] DEFAULT (N''),
[_CX_NEWGFEUDATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_NEWGFEUDATE] DEFAULT (N''),
[_SYS_X170] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X170] DEFAULT (N''),
[_CX_HPMLSTAMP_16] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_HPMLSTAMP_16] DEFAULT (N''),
[_CX_SMARTTAX] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SMARTTAX] DEFAULT (N''),
[_SYS_X139] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X139] DEFAULT (N''),
[_SYS_X140] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X140] DEFAULT (N''),
[_SYS_X141] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X141] DEFAULT (N''),
[_SYS_X174] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X174] DEFAULT (N''),
[_SYS_X161] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X161] DEFAULT (N''),
[_SYS_X168] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X168] DEFAULT (N''),
[_SYS_X169] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X169] DEFAULT (N''),
[_CX_NEWGFEUDATEDIR] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_NEWGFEUDATEDIR] DEFAULT (N''),
[_SYS_X138] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X138] DEFAULT (N''),
[_SYS_X157] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X157] DEFAULT (N''),
[_2148] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2148] DEFAULT (N''),
[_CX_SECCANCEL5] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCANCEL5] DEFAULT (N''),
[_CX_CLSSUBTOCLST] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSSUBTOCLST] DEFAULT (N''),
[_CX_FEDNUMB] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FEDNUMB] DEFAULT (N''),
[_CX_PROBCONDODESC] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBCONDODESC] DEFAULT (N''),
[_CX_SECCANCEL3] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCANCEL3] DEFAULT (N''),
[_CX_SECRUSH] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECRUSH] DEFAULT (N''),
[_CX_SECRELOCK4] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECRELOCK4] DEFAULT (N''),
[_CX_UWINVESTOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWINVESTOR] DEFAULT (N''),
[_CX_SECRELOCK] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECRELOCK] DEFAULT (N''),
[_CX_CLSRECT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSRECT] DEFAULT (N''),
[_CX_SECCANCEL2] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCANCEL2] DEFAULT (N''),
[_CX_CLSASSTOCLST] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSASSTOCLST] DEFAULT (N''),
[_CX_SECCANCEL4] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCANCEL4] DEFAULT (N''),
[_CX_NAMECONDOPROB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_NAMECONDOPROB] DEFAULT (N''),
[_CX_SECPENDING] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECPENDING] DEFAULT (N''),
[_MORNET_X40] [varchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_MORNET_X40] DEFAULT (N''),
[_CX_SECRELOCK3] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECRELOCK3] DEFAULT (N''),
[_CX_COPYAPPRVALUE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COPYAPPRVALUE] DEFAULT (N''),
[_CX_SECRELOCK5] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECRELOCK5] DEFAULT (N''),
[_CX_SECRELOCK2] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECRELOCK2] DEFAULT (N''),
[_CX_UWINVTOUW] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWINVTOUW] DEFAULT (N''),
[_CX_SECCANCEL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCANCEL] DEFAULT (N''),
[_CX_PROBCONDO] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBCONDO] DEFAULT (N''),
[_CX_UWINV] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWINV] DEFAULT (N''),
[_202] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_202] DEFAULT (N''),
[_1091] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1091] DEFAULT (N''),
[_NEWHUD_X764] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X764] DEFAULT (N''),
[_CX_SECPENDNOTES] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECPENDNOTES] DEFAULT (N''),
[_NEWHUD_X758] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X758] DEFAULT (N''),
[_CX_COMPAREINV] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREINV] DEFAULT (N''),
[_3135] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3135] DEFAULT (N''),
[_3160] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3160] DEFAULT (N''),
[_3162] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3162] DEFAULT (N''),
[_3166] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3166] DEFAULT (N''),
[_3169] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3169] DEFAULT (N''),
[_3168] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3168] DEFAULT (N''),
[_NEWHUD_X766] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X766] DEFAULT (N''),
[_NEWHUD_X752] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X752] DEFAULT (N''),
[_NEWHUD_X751] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X751] DEFAULT (N''),
[_1646] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1646] DEFAULT (N''),
[_3139] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3139] DEFAULT (N''),
[_3138] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3138] DEFAULT (N''),
[_NEWHUD_X765] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X765] DEFAULT (N''),
[_NEWHUD_X754] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X754] DEFAULT (N''),
[_NEWHUD_X759] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X759] DEFAULT (N''),
[_3141] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3141] DEFAULT (N''),
[_NEWHUD_X760] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X760] DEFAULT (N''),
[_3158] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3158] DEFAULT (N''),
[_NEWHUD_X767] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X767] DEFAULT (N''),
[_NEWHUD_X753] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X753] DEFAULT (N''),
[_NEWHUD_X763] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X763] DEFAULT (N''),
[_3157] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3157] DEFAULT (N''),
[_1106] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1106] DEFAULT (N''),
[_3159] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3159] DEFAULT (N''),
[_NEWHUD_X756] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X756] DEFAULT (N''),
[_L259] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_L259] DEFAULT (N''),
[_ORGID] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ORGID] DEFAULT (N''),
[_411] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_411] DEFAULT (N''),
[_CX_CLSVOENEED] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSVOENEED] DEFAULT (N''),
[_CX_PROBDISPUTESUB] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBDISPUTESUB] DEFAULT (N''),
[_CX_PROBDISPUTECOND] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBDISPUTECOND] DEFAULT (N''),
[_CX_PROBDISPUTECLS] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBDISPUTECLS] DEFAULT (N''),
[_CX_UWLIASON] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWLIASON] DEFAULT (N''),
[_4005] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_4005] DEFAULT (N''),
[_4001] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_4001] DEFAULT (N''),
[_2251] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2251] DEFAULT (N''),
[_CX_CHKREQCMTS_3] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQCMTS_3] DEFAULT (N''),
[_CX_CHKREQCMTS] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQCMTS] DEFAULT (N''),
[_CX_CHKREQCMTS_1] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQCMTS_1] DEFAULT (N''),
[_CX_CHKREQCMTS_2] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQCMTS_2] DEFAULT (N''),
[_955] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_955] DEFAULT (N''),
[_CX_RUSHCONDOCOND] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RUSHCONDOCOND] DEFAULT (N''),
[_CX_RUSHAUDIT] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RUSHAUDIT] DEFAULT (N''),
[_CX_RUSHCONDO] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RUSHCONDO] DEFAULT (N''),
[_2374] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2374] DEFAULT (N''),
[_CX_L360CMPN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_L360CMPN] DEFAULT (N''),
[_CX_CPGNKEYWRD] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CPGNKEYWRD] DEFAULT (N''),
[_1728] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1728] DEFAULT (N''),
[_4003] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_4003] DEFAULT (N''),
[LOCKRATE_60] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_60] DEFAULT (N''),
[_4007] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_4007] DEFAULT (N''),
[_1012] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1012] DEFAULT (N''),
[_CX_SFC1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SFC1] DEFAULT (N''),
[LOCKRATE_REQUESTPENDING] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_REQUESTPENDING] DEFAULT (N''),
[_CX_SFC3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SFC3] DEFAULT (N''),
[_425] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_425] DEFAULT (N''),
[_CX_MICERTNUM] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_MICERTNUM] DEFAULT (N''),
[_CX_SFC6] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SFC6] DEFAULT (N''),
[_CX_SFC5] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SFC5] DEFAULT (N''),
[_CX_SFC4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SFC4] DEFAULT (N''),
[_CX_SFC2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SFC2] DEFAULT (N''),
[_CX_CLOSEFACTR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLOSEFACTR] DEFAULT (N''),
[_CX_PROPTAXZIP_4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROPTAXZIP_4] DEFAULT (N''),
[_CX_PROPTAXSTATE_2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROPTAXSTATE_2] DEFAULT (N''),
[_CX_PROPTAXSTATE_5] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROPTAXSTATE_5] DEFAULT (N''),
[_CX_INSWNDSTATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSWNDSTATE] DEFAULT (N''),
[_CX_INSHAZSTATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSHAZSTATE] DEFAULT (N''),
[_CX_SECINVESTOR_10] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECINVESTOR_10] DEFAULT (N''),
[_3174] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3174] DEFAULT (N''),
[_1401] [varchar] (130) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1401] DEFAULT (N''),
[_DISCLOSURE_X1094] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DISCLOSURE_X1094] DEFAULT (N''),
[_3893] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3893] DEFAULT (N''),
[_DISCLOSURE_X1089] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DISCLOSURE_X1089] DEFAULT (N''),
[_POPT_X220] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X220] DEFAULT (N''),
[_POPT_X293] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X293] DEFAULT (N''),
[_POPT_X177] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X177] DEFAULT (N''),
[_POPT_X157] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X157] DEFAULT (N''),
[_POPT_X200] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X200] DEFAULT (N''),
[_POPT_X184] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X184] DEFAULT (N''),
[_POPT_X162] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X162] DEFAULT (N''),
[_1666] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1666] DEFAULT (N''),
[_POPT_X193] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X193] DEFAULT (N''),
[_POPT_X339] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X339] DEFAULT (N''),
[_POPT_X306] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X306] DEFAULT (N''),
[_POPT_X336] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X336] DEFAULT (N''),
[_POPT_X299] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X299] DEFAULT (N''),
[_1643] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1643] DEFAULT (N''),
[_POPT_X179] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X179] DEFAULT (N''),
[_POPT_X159] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X159] DEFAULT (N''),
[_POPT_X213] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X213] DEFAULT (N''),
[_POPT_X303] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X303] DEFAULT (N''),
[_POPT_X345] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X345] DEFAULT (N''),
[_POPT_X344] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X344] DEFAULT (N''),
[_POPT_X340] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X340] DEFAULT (N''),
[_POPT_X212] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X212] DEFAULT (N''),
[_POPT_X314] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X314] DEFAULT (N''),
[_POPT_X304] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X304] DEFAULT (N''),
[_CX_ISDIGITALMORTGAGE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ISDIGITALMORTGAGE] DEFAULT (N''),
[_CX_POA_CLOSINGREMEDY] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_POA_CLOSINGREMEDY] DEFAULT (N''),
[_CX_RUSH_UW_REGION] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RUSH_UW_REGION] DEFAULT (N''),
[_CX_ONLINEPRICING] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ONLINEPRICING] DEFAULT (N''),
[_CX_UWINITIALLIASON] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWINITIALLIASON] DEFAULT (N''),
[_CX_ISDMLENDERCREDITELIGIBLE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ISDMLENDERCREDITELIGIBLE] DEFAULT (N''),
[_CX_CHECKEXP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHECKEXP] DEFAULT (N''),
[_CX_TIMESTAMP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_TIMESTAMP] DEFAULT (N''),
[_CX_3RD_PARTY_WIRES] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_3RD_PARTY_WIRES] DEFAULT (N''),
[_3164] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3164] DEFAULT (N''),
[_LE3_X21] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LE3_X21] DEFAULT (N''),
[_LE3_X20] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LE3_X20] DEFAULT (N''),
[_LE2_X28] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LE2_X28] DEFAULT (N''),
[_NEWHUD2_X1514] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X1514] DEFAULT (N''),
[_NEWHUD2_X3923] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3923] DEFAULT (N''),
[_NEWHUD2_X4121] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X4121] DEFAULT (N'')
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[ti_LOANXDB_S_02_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_02]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF NOT EXISTS( SELECT 1 FROM emdbuser.LoanSummary ls JOIN inserted i ON i.XRefID = ls.XRefID)
	BEGIN

		INSERT INTO emdbuser.LoanSummary([Guid]
										,[LoanNumber]
										,[LoanFolder] 
										,[LoanName]
										,[Status]
										,[loanStatus]
										,[RateLockStatus]
										,[RateIsLocked]
										,[Investor]
										,[Broker]
										,XRefID
										,LastModified
										,City
										,TitleVendor
										,BorrowerSex
										,LoanProgram
										,LoanChannel
										,LockRequestPending
										,LoanProcessorName
										,loanDocTypeCode)
		SELECT NEWID()
			  ,CAST(i._364 AS VARCHAR(30))
			  ,''
			  ,NEWID()
			  ,'A'
			  ,''
			  ,''
			  ,''
			  ,''
			  ,''
			  ,XRefID
			  ,GETDATE()
			  ,_12
			  ,_411
			  ,_471
			  ,CAST(_1401 AS VARCHAR(100))
			  ,CASE WHEN _2626 = 'Correspondent' THEN 4 WHEN _2626 = 'Brokered' THEN 3 WHEN _2626 = 'Banked - Retail' THEN 1 ELSE _2626 END
			  ,LOCKRATE_REQUESTPENDING
			  ,_362
			  ,CASE
					WHEN _MORNET_X67 = 'Alternative' THEN 'A'
					WHEN _MORNET_X67 = 'StreamlineRefinance' THEN 'B'
					WHEN _MORNET_X67 = 'NoDocumentation' THEN 'C'
					WHEN _MORNET_X67 = 'NoRatio' THEN 'D'
					WHEN _MORNET_X67 = 'LimitedDocumentation' THEN 'E'
					WHEN _MORNET_X67 = 'FullDocumentation' THEN 'F'
					WHEN _MORNET_X67 = 'NoIncomeNoAssetsOn1003' THEN 'G'
					WHEN _MORNET_X67 = 'NoAssetsOn1003' THEN 'H'
					WHEN _MORNET_X67 = 'NoIncomeOn1003' THEN 'J'
					WHEN _MORNET_X67 = 'NoVerificationOfStatedIncomeEmploymentOrAssets' THEN 'K'
					WHEN _MORNET_X67 = 'NoVerificationOfStatedIncomeOrAssets' THEN 'L'
					WHEN _MORNET_X67 = 'NoVerificationOfStatedAssets' THEN 'M'
					WHEN _MORNET_X67 = 'NoVerificationOfStatedIncome' THEN 'O'
					WHEN _MORNET_X67 = 'VerbalVerificationOfEmployment' THEN 'P'
					WHEN _MORNET_X67 = 'OnePaystub' THEN 'Q'
					WHEN _MORNET_X67 = 'Reduced' THEN 'R'
					WHEN _MORNET_X67 = 'OnePaystubAndOneW2AndVerbalVerificationOfEmploymentOrOneYear1040' THEN 'T'
					WHEN _MORNET_X67 = 'NoIncomeNoEmploymentNoAssetsOn1003' THEN 'U'
					WHEN _MORNET_X67 = '' THEN ''
					ELSE NULL
			   END
		FROM inserted i

	END
	ELSE

		UPDATE ls
		SET  LoanNumber = CAST(i._364 AS VARCHAR(30))
			,City = i._12
			,TitleVendor = i._411
			,BorrowerSex = i._471
			,LoanProgram = CAST(_1401 AS VARCHAR(100))
			,LoanChannel = CASE WHEN i._2626 = 'Correspondent' THEN 4 WHEN i._2626 = 'Brokered' THEN 3 WHEN i._2626 = 'Banked - Retail' THEN 1 ELSE i._2626 END
			,LastModified = GETDATE()
			,LockRequestPending = i.LOCKRATE_REQUESTPENDING
			,LoanProcessorName = i._362
			,loanDocTypeCode = CASE
									WHEN i._MORNET_X67 = 'Alternative' THEN 'A'
									WHEN i._MORNET_X67 = 'StreamlineRefinance' THEN 'B'
									WHEN i._MORNET_X67 = 'NoDocumentation' THEN 'C'
									WHEN i._MORNET_X67 = 'NoRatio' THEN 'D'
									WHEN i._MORNET_X67 = 'LimitedDocumentation' THEN 'E'
									WHEN i._MORNET_X67 = 'FullDocumentation' THEN 'F'
									WHEN i._MORNET_X67 = 'NoIncomeNoAssetsOn1003' THEN 'G'
									WHEN i._MORNET_X67 = 'NoAssetsOn1003' THEN 'H'
									WHEN i._MORNET_X67 = 'NoIncomeOn1003' THEN 'J'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedIncomeEmploymentOrAssets' THEN 'K'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedIncomeOrAssets' THEN 'L'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedAssets' THEN 'M'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedIncome' THEN 'O'
									WHEN i._MORNET_X67 = 'VerbalVerificationOfEmployment' THEN 'P'
									WHEN i._MORNET_X67 = 'OnePaystub' THEN 'Q'
									WHEN i._MORNET_X67 = 'Reduced' THEN 'R'
									WHEN i._MORNET_X67 = 'OnePaystubAndOneW2AndVerbalVerificationOfEmploymentOrOneYear1040' THEN 'T'
									WHEN i._MORNET_X67 = 'NoIncomeNoEmploymentNoAssetsOn1003' THEN 'U'
									WHEN i._MORNET_X67 = '' THEN ''
									ELSE NULL
							   END
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[tu_LOANXDB_S_02_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_02]
   AFTER UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF (UPDATE(_12) OR UPDATE(_411) OR UPDATE(_471) OR UPDATE(_1401) OR UPDATE(_364) OR UPDATE(_2626) OR UPDATE(LOCKRATE_REQUESTPENDING) OR UPDATE(_362))

		UPDATE ls
		SET  LoanNumber = CAST(i._364 AS VARCHAR(30))
			,City = i._12
			,TitleVendor = i._411
			,BorrowerSex = i._471
			,LoanProgram = CAST(_1401 AS VARCHAR(100))
			,LoanChannel = CASE WHEN i._2626 = 'Correspondent' THEN 4 WHEN i._2626 = 'Brokered' THEN 3 WHEN i._2626 = 'Banked - Retail' THEN 1 ELSE i._2626 END
			,LastModified = GETDATE()
			,LockRequestPending = i.LOCKRATE_REQUESTPENDING
			,LoanProcessorName = i._362
			,loanDocTypeCode = CASE
									WHEN i._MORNET_X67 = 'Alternative' THEN 'A'
									WHEN i._MORNET_X67 = 'StreamlineRefinance' THEN 'B'
									WHEN i._MORNET_X67 = 'NoDocumentation' THEN 'C'
									WHEN i._MORNET_X67 = 'NoRatio' THEN 'D'
									WHEN i._MORNET_X67 = 'LimitedDocumentation' THEN 'E'
									WHEN i._MORNET_X67 = 'FullDocumentation' THEN 'F'
									WHEN i._MORNET_X67 = 'NoIncomeNoAssetsOn1003' THEN 'G'
									WHEN i._MORNET_X67 = 'NoAssetsOn1003' THEN 'H'
									WHEN i._MORNET_X67 = 'NoIncomeOn1003' THEN 'J'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedIncomeEmploymentOrAssets' THEN 'K'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedIncomeOrAssets' THEN 'L'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedAssets' THEN 'M'
									WHEN i._MORNET_X67 = 'NoVerificationOfStatedIncome' THEN 'O'
									WHEN i._MORNET_X67 = 'VerbalVerificationOfEmployment' THEN 'P'
									WHEN i._MORNET_X67 = 'OnePaystub' THEN 'Q'
									WHEN i._MORNET_X67 = 'Reduced' THEN 'R'
									WHEN i._MORNET_X67 = 'OnePaystubAndOneW2AndVerbalVerificationOfEmploymentOrOneYear1040' THEN 'T'
									WHEN i._MORNET_X67 = 'NoIncomeNoEmploymentNoAssetsOn1003' THEN 'U'
									WHEN i._MORNET_X67 = '' THEN ''
									ELSE NULL
							   END
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
ALTER TABLE [emdbuser].[LOANXDB_S_02] ADD CONSTRAINT [PK_LOANXDB_S_02_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_CHILHQSQLDB_Warehouse_DailyLocks_02] ON [emdbuser].[LOANXDB_S_02] ([_2278], [_CX_SECPENDING]) INCLUDE ([_1130], [_1401], [_364], [_CX_SECINVESTOR_10], [XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANXDB_S_02_364] ON [emdbuser].[LOANXDB_S_02] ([_364]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_02__471] ON [emdbuser].[LOANXDB_S_02] ([_471]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_02__FR0107] ON [emdbuser].[LOANXDB_S_02] ([_FR0107], [_2574]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_02__VEND_X398_Includes] ON [emdbuser].[LOANXDB_S_02] ([_VEND_X398], [_2574]) INCLUDE ([_2278], [_364], [_411], [_471], [_CX_SECINVESTOR_10], [_CX_SECPENDING], [XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
