CREATE TABLE [emdbuser].[LOANXDB_D_06]
(
[XrefId] [int] NOT NULL,
[_CX_APPRRECDDATE4_4] [datetime] NULL,
[_CX_UCC3SUBMIT] [datetime] NULL,
[_CX_CCAUTHSIGDATE] [datetime] NULL,
[_CX_VOE_ASSIGNMENT_DATE] [datetime] NULL,
[_CX_GR_INS_DATE] [datetime] NULL,
[_CX_GRANT_FUNDS_SEND_DATE] [datetime] NULL,
[_CX_POAAPPROVEDDATE] [datetime] NULL,
[_CX_VALUATION_WAIVER_SENT] [datetime] NULL,
[_CX_VALUATION_WAIVER_NEEDED] [datetime] NULL,
[_3624] [datetime] NULL,
[_CX_VALUATION_CONDITION_RECD] [datetime] NULL,
[_CX_VALUATION_CONDITION_SENT] [datetime] NULL,
[_CX_FINAL_INSP_SENT] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_D_06] ADD CONSTRAINT [PK_LOANXDB_D_06_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
