CREATE TABLE [emdbuser].[LOANXDB_X_05]
(
[XRefId] [int] NOT NULL,
[InsertBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_loanxdb_x_05_InsertBy] DEFAULT (replace(suser_sname(),'GRCORP\\','')),
[InsertDT] [datetime] NOT NULL CONSTRAINT [df_loanxdb_x_05_InsertDT] DEFAULT (getdate()),
[LastUpdateBy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_loanxdb_x_05_LastUpdateBy] DEFAULT (replace(suser_sname(),'GRCORP\\','')),
[LastUpdateDT] [datetime] NOT NULL CONSTRAINT [df_loanxdb_x_05_LastUpdateDT] DEFAULT (getdate()),
[Revision] [int] NOT NULL CONSTRAINT [df_loanxdb_x_05_Revision] DEFAULT ((0)),
[_CX_CC229_15] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_CC230_15] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_CLOSINGSUBMITDATE] [datetime] NULL,
[_CX_CLOSINGSUBMISSIONNOTES] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanTeamMember_Name_OpsAssist-MC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanTeamMember_Name_OpsAssist-LC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanTeamMember_Name_OpsAssist-CC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanTeamMember_Name_OpsAssist-S] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RAAE_DENIED] [datetime] NULL,
[_CX_RAAE_APPROVED_COND_DT] [datetime] NULL,
[_CX_PREMIER_BUILDER] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_713] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_MORNET_X72] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_MORNET_X27] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_SOURCE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_ACCT_EXEC] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_DB_RECEIVED] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_CLIENT_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_CLIENT_NAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_BALANCE] [decimal] (23, 10) NULL,
[_CX_RELO_BDA_REQUESTED] [datetime] NULL,
[_CX_RELO_BDA_SIGNED] [datetime] NULL,
[_CX_RELO_BENEFIT_EXP] [datetime] NULL,
[_CX_RELO_BENEFIT_IMPACT] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_BROKER_REGISTRATION] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_CAP_OTHER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_COMPANY_CID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_COMPANY] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_CONSULTANT_EMAIL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_CONSULTANT_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_CONSULTANT_PHONE] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_DB_COVERS_POINTS] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_DB_PAID] [datetime] NULL,
[_CX_RELO_DIRECTBILL_AUTH] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_DIRECTBILL_SPECIALIS] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_DIRECTBILL_STATUS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_DIV_NUMBER] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_EMPLOYER_NAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_EVIP] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_FEE_CODE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_FEE_TYPE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_FILE_NUMBER] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_INFO_CONSENT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_INVOICE_AMOUNT] [decimal] (23, 10) NULL,
[_CX_RELO_INVOICE_DATE] [datetime] NULL,
[_CX_RELO_VIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_BUYOUT_OPTION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_BREG_IMPACT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_TRANSFER_DATE] [datetime] NULL,
[_CX_UW_EXCP_APRV_CMNTS] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_UWREGION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_CLOSEOUTFUNDS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_HMDA_X28] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_RELO_SUBSIDY_ELIGIBLE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_GUARDIAN_DISCLOSED] [datetime] NULL,
[_CX_APPRFORMTYPE_LENDERX] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CX_EMPLOAN_RESTRICTED] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_X_05] ADD CONSTRAINT [pk_LOANXDB_X_05] PRIMARY KEY CLUSTERED  ([XRefId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
