CREATE TABLE [emdbuser].[LOANXDB_S_11]
(
[XrefId] [int] NOT NULL,
[_CX_SUBREBUTDESC] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SUBREBUTDESC] DEFAULT (N''),
[_CX_L360GRCOMSESSIONID] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_L360GRCOMSESSIONID] DEFAULT (N''),
[_CX_L360PPCCAMPAIGN] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_L360PPCCAMPAIGN] DEFAULT (N'')
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_S_11] ADD CONSTRAINT [PK_LOANXDB_S_11_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
