CREATE TABLE [emdbuser].[LOANXDB_S_22]
(
[XrefId] [int] NOT NULL,
[_CX_UWXR_POD_COMMENTS] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXR_POD_COMMENTS] DEFAULT (N''),
[_CX_UW_LS_COLLATERAL] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UW_LS_COLLATERAL] DEFAULT (N''),
[_CX_UWXRA_5] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXRA_5] DEFAULT (N''),
[_CX_UWXRA_4] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXRA_4] DEFAULT (N''),
[_CX_UWXRA_7] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXRA_7] DEFAULT (N''),
[_CX_UWXRA_6] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXRA_6] DEFAULT (N''),
[_CX_UWXRA_9] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXRA_9] DEFAULT (N'')
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_S_22] ADD CONSTRAINT [PK_LOANXDB_S_22_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
