CREATE TABLE [emdbuser].[LoanXRef]
(
[XRefID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[LoanGuid] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LoanXRef] ADD CONSTRAINT [PK_LoanXRef] PRIMARY KEY CLUSTERED  ([XRefID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LoanXRef_LoanGuid] ON [emdbuser].[LoanXRef] ([LoanGuid]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
