CREATE TABLE [emdbuser].[LOANXDB_S_20]
(
[XrefId] [int] NOT NULL,
[_FL0305] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0305] DEFAULT (N''),
[_CE0210] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0210] DEFAULT (N''),
[_CE0202] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0202] DEFAULT (N''),
[_CE0207] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0207] DEFAULT (N''),
[_CE0204] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0204] DEFAULT (N''),
[_CE0205] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0205] DEFAULT (N''),
[_CE0209] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0209] DEFAULT (N''),
[_DD0302] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0302] DEFAULT (N''),
[_BE0237] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0237] DEFAULT (N''),
[_DD0324] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0324] DEFAULT (N''),
[_DD0306] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0306] DEFAULT (N''),
[_DD0307] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0307] DEFAULT (N''),
[_DD0304] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0304] DEFAULT (N''),
[_DD0305] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0305] DEFAULT (N''),
[_DD0308] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0308] DEFAULT (N''),
[_BE0210] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0210] DEFAULT (N''),
[_BE0217] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0217] DEFAULT (N''),
[_BE0215] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0215] DEFAULT (N''),
[_BE0209] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0209] DEFAULT (N''),
[_CE0215] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0215] DEFAULT (N''),
[_CE0237] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0237] DEFAULT (N''),
[_CE0305] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0305] DEFAULT (N''),
[_BE0305] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0305] DEFAULT (N''),
[_BE0304] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0304] DEFAULT (N''),
[_FL0310] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0310] DEFAULT (N''),
[_FL0307] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0307] DEFAULT (N''),
[_CX_ADTRK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ADTRK] DEFAULT (N''),
[_CE0310] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0310] DEFAULT (N''),
[_CE0307] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0307] DEFAULT (N''),
[_CE0306] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0306] DEFAULT (N''),
[_CE0337] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0337] DEFAULT (N''),
[_CE0304] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0304] DEFAULT (N''),
[_CE0309] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0309] DEFAULT (N''),
[_BE0337] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0337] DEFAULT (N''),
[_BE0302] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0302] DEFAULT (N''),
[_BE0307] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0307] DEFAULT (N''),
[_BE0310] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0310] DEFAULT (N''),
[_BE0317] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0317] DEFAULT (N''),
[_BE0315] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0315] DEFAULT (N''),
[_BE0309] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0309] DEFAULT (N''),
[_CE0317] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0317] DEFAULT (N''),
[_CE0315] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0315] DEFAULT (N''),
[_CE0302] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0302] DEFAULT (N''),
[_CX_TRACK_FASTPASS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_TRACK_FASTPASS] DEFAULT (N''),
[_CX_FASTPASS_STRIKE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FASTPASS_STRIKE] DEFAULT (N''),
[_DD0124] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0124] DEFAULT (N''),
[LOCKRATE_REQUESTSTATUS] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_REQUESTSTATUS] DEFAULT (N''),
[_CX_CX_CLOSEOUT_NOTES] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CX_CLOSEOUT_NOTES] DEFAULT (N''),
[LOCKRATE_RATESTATUS] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_RATESTATUS] DEFAULT (N''),
[_2311] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2311] DEFAULT (N''),
[LOCKRATE_RATEREQUESTSTATUS] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_RATEREQUESTSTATUS] DEFAULT (N''),
[_CX_TRCLSLC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_TRCLSLC] DEFAULT (N''),
[_CX_COP_OVERRIDE_YN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COP_OVERRIDE_YN] DEFAULT (N''),
[_2386] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2386] DEFAULT (N''),
[_2384] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2384] DEFAULT (N''),
[_2382] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2382] DEFAULT (N''),
[_2380] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2380] DEFAULT (N''),
[_2388] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2388] DEFAULT (N''),
[_2394] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2394] DEFAULT (N''),
[_2392] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2392] DEFAULT (N''),
[_2390] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2390] DEFAULT (N''),
[_REGZGFE_X8] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_REGZGFE_X8] DEFAULT (N''),
[_2378] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2378] DEFAULT (N''),
[_FE0104_P2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0104_P2] DEFAULT (N''),
[_CX_LOCK_COMPARE_ORD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LOCK_COMPARE_ORD] DEFAULT (N''),
[_CE0105_P2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0105_P2] DEFAULT (N''),
[_CE0106_P2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0106_P2] DEFAULT (N''),
[_CE0107_P2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0107_P2] DEFAULT (N''),
[_CE0102_P2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0102_P2] DEFAULT (N''),
[_CX_APPREMAILCOMMENTS_4] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPREMAILCOMMENTS_4] DEFAULT (N''),
[_CX_VELOCITY_CAMPAIGN_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_VELOCITY_CAMPAIGN_ID] DEFAULT (N''),
[_CX_L360REFERENCESOURCE] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_L360REFERENCESOURCE] DEFAULT (N''),
[_CX_APPREMAILCOMMENTS2_4] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPREMAILCOMMENTS2_4] DEFAULT (N''),
[_CE0104_P2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0104_P2] DEFAULT (N''),
[_1729] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1729] DEFAULT (N''),
[_QM_X135] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X135] DEFAULT (N''),
[_QM_X24] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X24] DEFAULT (N''),
[_QM_X25] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X25] DEFAULT (N''),
[_QM_X34] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X34] DEFAULT (N''),
[_QM_X30] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X30] DEFAULT (N''),
[_QM_X26] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X26] DEFAULT (N''),
[_QM_X33] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X33] DEFAULT (N''),
[_QM_X27] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X27] DEFAULT (N''),
[_QM_X28] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X28] DEFAULT (N''),
[_QM_X29] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X29] DEFAULT (N''),
[_QM_X23] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X23] DEFAULT (N''),
[_QM_X31] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X31] DEFAULT (N''),
[_1726] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1726] DEFAULT (N''),
[_1727] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1727] DEFAULT (N''),
[_QM_X124] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X124] DEFAULT (N''),
[_NEWHUD_X1067] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1067] DEFAULT (N''),
[_QM_X51] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X51] DEFAULT (N''),
[_QM_X62] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X62] DEFAULT (N''),
[_QM_X53] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X53] DEFAULT (N''),
[_QM_X54] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X54] DEFAULT (N''),
[_QM_X60] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X60] DEFAULT (N''),
[_QM_X57] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X57] DEFAULT (N''),
[_QM_X63] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X63] DEFAULT (N''),
[_QM_X64] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X64] DEFAULT (N''),
[_QM_X65] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X65] DEFAULT (N''),
[_QM_X66] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X66] DEFAULT (N''),
[_QM_X67] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X67] DEFAULT (N''),
[_QM_X81] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X81] DEFAULT (N''),
[_QM_X82] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X82] DEFAULT (N''),
[_QM_X80] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X80] DEFAULT (N''),
[_QM_X35] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X35] DEFAULT (N''),
[_QM_X36] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_QM_X36] DEFAULT (N''),
[_CX_ECOA_HPML_A1] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ECOA_HPML_A1] DEFAULT (N''),
[_CX_APPRAISAL_EMAIL] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRAISAL_EMAIL] DEFAULT (N''),
[_CX_ECOA_HPML_1] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ECOA_HPML_1] DEFAULT (N''),
[_L140] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_L140] DEFAULT (N''),
[_CX_APLD_OVERRIDE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APLD_OVERRIDE] DEFAULT (N''),
[_CX_LPR_NEW_CON] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LPR_NEW_CON] DEFAULT (N''),
[_2982] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2982] DEFAULT (N''),
[_CX_SHIPDIFUNDINGDOCS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHIPDIFUNDINGDOCS] DEFAULT (N''),
[_SYS_X324] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X324] DEFAULT (N''),
[_CX_FLLWUP_BRWR_4] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FLLWUP_BRWR_4] DEFAULT (N'')
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[ti_LOANXDB_S_20_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_20]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF NOT EXISTS( SELECT 1 FROM emdbuser.LoanSummary ls JOIN inserted i ON i.XRefID = ls.XRefID)
	BEGIN

		INSERT INTO emdbuser.LoanSummary([Guid]
										,[LoanNumber]
										,[LoanFolder] 
										,[LoanName]
										,[Status]
										,[loanStatus]
										,[RateLockStatus]
										,[RateIsLocked]
										,[Investor]
										,[Broker]
										,[XRefID]
										,LastModified
										,UnderwriterVendor)
		SELECT NEWID()
			  ,''
			  ,''
			  ,NEWID()
			  ,'A'
			  ,''
			  ,''
			  ,''
			  ,''
			  ,''
			  ,XRefID
			  ,GETDATE()
			  ,_REGZGFE_X8
		FROM inserted i
	END
	ELSE

		UPDATE ls
		SET  UnderwriterVendor = i._REGZGFE_X8
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[tu_LOANXDB_S_20_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_20]
   AFTER UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF (UPDATE(_REGZGFE_X8))

		UPDATE ls
		SET  UnderwriterVendor = i._REGZGFE_X8
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
ALTER TABLE [emdbuser].[LOANXDB_S_20] ADD CONSTRAINT [PK_LOANXDB_S_20_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
