CREATE TABLE [emdbuser].[LOANXDB_S_27]
(
[XrefId] [int] NOT NULL,
[_CX_INSURANCE_NOTES] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSURANCE_NOTES] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_S_27] ADD CONSTRAINT [PK_LOANXDB_S_27_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
