CREATE TABLE [emdbuser].[zzz_DELETE_LoanSummary_InFile]
(
[Guid] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoanNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoanFolder] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoanName] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Address1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoBorrowerFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoBorrowerLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanOfficerId] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanProcessorId] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanOfficerName] [varchar] (101) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanProcessorName] [varchar] (101) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanPurpose] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondMortgage] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentMilestoneName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentMilestoneDate] [smalldatetime] NULL,
[NextMilestoneName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextMilestoneDate] [datetime] NULL,
[PrevMilestoneGroupDate] [datetime] NULL,
[CurrentCoreMilestoneName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextCoreMilestoneName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessorReviewed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockExpirationDate] [smalldatetime] NULL,
[Lender] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnderwriterVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisalVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TitleVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EscrowVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FloodVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocPrepVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HazardInsuranceVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MortgageInsuranceVendor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferralSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateFileOpened] [smalldatetime] NULL,
[DateSentToProcessing] [datetime] NULL,
[DateSubmittedToLender] [datetime] NULL,
[DateApprovalReceived] [datetime] NULL,
[DateDocsSigned] [datetime] NULL,
[DateFunded] [smalldatetime] NULL,
[DateOfEstimatedCompletion] [datetime] NULL,
[DateCompleted] [smalldatetime] NULL,
[LastModified] [datetime] NULL,
[ActionTaken] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActionTakenDate] [smalldatetime] NULL,
[CensusTract] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MSA] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerSex] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoBorrowerSex] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerRace] [varchar] (180) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoBorrowerRace] [varchar] (180) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerEthnicity] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoBorrowerEthnicity] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanCloserId] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanCloserName] [varchar] (101) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LinkGuid] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loanStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[loanDocTypeCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockRequestDate] [smalldatetime] NULL,
[RateLockStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RateIsLocked] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Investor] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Broker] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoanProgram] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccupancyStatus] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EscrowWaived] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvestorStatus] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvestorStatusDate] [datetime] NULL,
[TradeGuid] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TradeNumber] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amortization] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateShipped] [datetime] NULL,
[DatePurchased] [datetime] NULL,
[ISStatementDue] [datetime] NULL,
[ISPaymentDue] [datetime] NULL,
[ISEscrowDue] [datetime] NULL,
[RegistrationExpiredDate] [datetime] NULL,
[InvestorDeliveryDate] [datetime] NULL,
[CurrentMilestoneID] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextMilestoneID] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loanChannel] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockRequested] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockRequestPending] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerName] [varchar] (102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoBorrowerName] [varchar] (102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppraisedValue] [money] NULL,
[DownPayment] [money] NULL,
[LoanSource] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime] NULL,
[BuySideCommitted] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellSideCommitted] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adverse] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Completed] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DateOfFinalAction] [smalldatetime] NULL,
[LienPosition] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ARMAdjustmentDate] [smalldatetime] NULL,
[ISStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanAmount] [money] NULL,
[LoanRate] [decimal] (18, 5) NULL,
[Term] [int] NULL,
[LockDays] [int] NULL,
[LoanOfficerProfit] [money] NULL,
[LoanBrokerProfit] [money] NULL,
[LoanProcessorProfit] [money] NULL,
[ManagerProfit] [money] NULL,
[OtherProfit] [money] NULL,
[TotalCommissionByLoan] [money] NULL,
[TotalCommissionByProfit] [money] NULL,
[TotalAdditionalCommission] [money] NULL,
[LOCommissionByLoan] [money] NULL,
[LOCommissionByProfit] [money] NULL,
[LOAdditionalCommission] [money] NULL,
[TotalLoanAmount] [money] NULL,
[CreditScore] [int] NULL,
[LTV] [decimal] (18, 5) NULL,
[CLTV] [decimal] (18, 5) NULL,
[NetBuyPrice] [decimal] (18, 5) NULL,
[NetSellPrice] [decimal] (18, 5) NULL,
[TotalBuyPrice] [decimal] (18, 5) NULL,
[TotalSellPrice] [decimal] (18, 5) NULL,
[NetProfit] [money] NULL,
[DTITop] [decimal] (18, 5) NULL,
[DTIBottom] [decimal] (18, 5) NULL,
[ARMMargin] [decimal] (18, 5) NULL,
[ARMLifeCap] [decimal] (18, 5) NULL,
[ARMFloorRate] [decimal] (18, 5) NULL,
[ARMFirstRateAdjCap] [decimal] (18, 5) NULL,
[ISLatePaymentDate] [datetime] NULL,
[XRefID] [int] NOT NULL,
[TotalMonthlyIncome] [money] NULL,
[EstimatedValue] [money] NULL,
[LockExtensionRequestPending] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockCancellationRequestPending] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockIsCancelled] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelockRequestPending] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOLOID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOLPID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOCompanyID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOBranchID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPORegisterDate] [datetime] NULL,
[TPOSubmitDate] [datetime] NULL,
[UnderWriterApprovalDate] [datetime] NULL,
[UnderWriterSuspendedDate] [datetime] NULL,
[UnderWriterDeniedDate] [datetime] NULL,
[UnderWriterDifferentApprovedDate] [datetime] NULL,
[TPOSiteID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOArchived] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOLOName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOLPName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOCompanyName] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TPOBranchName] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LockCommitment] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LockStatusSortKey] [int] NOT NULL,
[LockAndRequestStatus] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockAndRequestSortKey] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockStatus] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CorrespondentTradeGuid] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorrespondentTradeNumber] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
