CREATE TABLE [emdbuser].[LOANXDB_S_10]
(
[XrefId] [int] NOT NULL,
[UWC_INTERNAL] [varchar] (4096) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFUWC_INTERNAL] DEFAULT (N''),
[_CX_CLSPKGTITLECOM] [varchar] (275) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSPKGTITLECOM] DEFAULT (N''),
[_CX_APPRSCHEDT1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRSCHEDT1] DEFAULT (N''),
[_CX_APPRSCHEDT3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRSCHEDT3] DEFAULT (N''),
[_2217] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2217] DEFAULT (N''),
[_2216] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2216] DEFAULT (N''),
[_37_P2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_37_P2] DEFAULT (N''),
[_36_P2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_36_P2] DEFAULT (N''),
[_CX_MCNAMECOPY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_MCNAMECOPY] DEFAULT (N''),
[_CX_CLOSERCOPY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLOSERCOPY] DEFAULT (N''),
[_CX_LCNAMECOPY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LCNAMECOPY] DEFAULT (N''),
[_CX_UWCONDOREV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWCONDOREV] DEFAULT (N''),
[_CX_UWCONDOREVTYP] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWCONDOREVTYP] DEFAULT (N''),
[_CX_INSMASCO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSMASCO] DEFAULT (N''),
[_CX_INSMASAGE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSMASAGE] DEFAULT (N''),
[_2962] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2962] DEFAULT (N''),
[LoanTeamMember_Email_LoanOfficer] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLoanTeamMember_Email_LoanOfficer] DEFAULT (N''),
[_CX_POOLNUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_POOLNUMBER] DEFAULT (N''),
[_2376] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2376] DEFAULT (N''),
[_CX_ACCCARDSECCODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCARDSECCODE] DEFAULT (N''),
[_CX_GRCOMSESSID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_GRCOMSESSID] DEFAULT (N''),
[_CX_GRCOMAPPID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_GRCOMAPPID] DEFAULT (N''),
[_CX_SUBREBUTEXIST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SUBREBUTEXIST] DEFAULT (N''),
[_CX_SUBREBCOND] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SUBREBCOND] DEFAULT (N''),
[_CX_SUBREBUTVAGUE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SUBREBUTVAGUE] DEFAULT (N''),
[_CX_SUBREBUTOTHER] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SUBREBUTOTHER] DEFAULT (N''),
[_CX_SUBREBUTUNNEC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SUBREBUTUNNEC] DEFAULT (N''),
[_CX_CONREBUTACCEPT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CONREBUTACCEPT] DEFAULT (N''),
[_CX_INCOMEEXP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INCOMEEXP] DEFAULT (N''),
[_CX_CREDITEXP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CREDITEXP] DEFAULT (N''),
[_CX_APPRAISALEXP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRAISALEXP] DEFAULT (N''),
[_CX_LEADSOURCE] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LEADSOURCE] DEFAULT (N''),
[_CX_ASSETEXP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ASSETEXP] DEFAULT (N''),
[_CX_CISUBMITDATA] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CISUBMITDATA] DEFAULT (N''),
[_2166] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2166] DEFAULT (N''),
[_2168] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2168] DEFAULT (N''),
[_2162] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2162] DEFAULT (N''),
[_2164] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2164] DEFAULT (N''),
[_2170] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2170] DEFAULT (N''),
[_2172] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2172] DEFAULT (N''),
[_2174] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2174] DEFAULT (N''),
[_2176] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2176] DEFAULT (N''),
[_L252] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_L252] DEFAULT (N''),
[_CX_ACHFLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACHFLAG] DEFAULT (N''),
[_60_P2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_60_P2] DEFAULT (N''),
[_1414_P2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1414_P2] DEFAULT (N''),
[_2849_P2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2849_P2] DEFAULT (N''),
[_67_P2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_67_P2] DEFAULT (N''),
[_FE0115_P2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0115_P2] DEFAULT (N''),
[_65_P2] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_65_P2] DEFAULT (N''),
[_FE0117_P2] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0117_P2] DEFAULT (N''),
[_CX_LOCKOVERIDE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LOCKOVERIDE] DEFAULT (N''),
[_CX_CCAUTHSIG] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CCAUTHSIG] DEFAULT (N''),
[_CX_COPOVERIDE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COPOVERIDE] DEFAULT (N''),
[_FR0106_P2] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0106_P2] DEFAULT (N''),
[_ULDD_X31] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ULDD_X31] DEFAULT (N''),
[_FR0107_P2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0107_P2] DEFAULT (N''),
[_FR0104_P2] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0104_P2] DEFAULT (N''),
[_FR0108_P2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0108_P2] DEFAULT (N''),
[_CX_GRV3APPID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_GRV3APPID] DEFAULT (N''),
[_CX_DOCFILEID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_DOCFILEID] DEFAULT (N''),
[_CX_LOCODE_1] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LOCODE_1] DEFAULT (N''),
[_CX_SANAME_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SANAME_1] DEFAULT (N''),
[_3000] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3000] DEFAULT (N''),
[_4002_P2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_4002_P2] DEFAULT (N''),
[_CX_GFEDSKNUMREVIEWS] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_GFEDSKNUMREVIEWS] DEFAULT (N''),
[_4000_P2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_4000_P2] DEFAULT (N''),
[LoanTeamMember_UserID_LoanCoordinator] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLoanTeamMember_UserID_LoanCoordinator] DEFAULT (N''),
[LoanTeamMember_UserID_MortgageConsultant] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLoanTeamMember_UserID_MortgageConsultant] DEFAULT (N''),
[LoanTeamMember_Name_MortgageConsultant] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLoanTeamMember_Name_MortgageConsultant] DEFAULT (N''),
[_1172] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1172] DEFAULT (N''),
[_CX_APPRAISALREQ] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRAISALREQ] DEFAULT (N''),
[_CX_RESTLTVCOMPLETE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RESTLTVCOMPLETE] DEFAULT (N''),
[_CX_RESTDTICOMPLETE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RESTDTICOMPLETE] DEFAULT (N''),
[_CX_OB_DESIREDPRICE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_OB_DESIREDPRICE] DEFAULT (N''),
[_CX_FHAOLDCASE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FHAOLDCASE] DEFAULT (N''),
[_CASASRN_X168] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASASRN_X168] DEFAULT (N''),
[_CASASRN_X167] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASASRN_X167] DEFAULT (N''),
[_CX_TRKINFOCLSNOTE] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_TRKINFOCLSNOTE] DEFAULT (N''),
[_2030] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2030] DEFAULT (N''),
[_CX_ENC_EMAIL_TRIG_01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ENC_EMAIL_TRIG_01] DEFAULT (N''),
[_CX_ENC_EMAIL_TRIG_03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ENC_EMAIL_TRIG_03] DEFAULT (N''),
[_CX_ENC_EMAIL_TRIG_05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ENC_EMAIL_TRIG_05] DEFAULT (N''),
[_CX_ENC_EMAIL_TRIG_04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ENC_EMAIL_TRIG_04] DEFAULT (N''),
[_ULDD_X9] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ULDD_X9] DEFAULT (N''),
[_ULDD_X178] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ULDD_X178] DEFAULT (N''),
[_ULDD_X8] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ULDD_X8] DEFAULT (N''),
[_ULDD_X132] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ULDD_X132] DEFAULT (N''),
[_ULDD_X7] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ULDD_X7] DEFAULT (N''),
[_676] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_676] DEFAULT (N''),
[_CX_CNDO_LITACPT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CNDO_LITACPT] DEFAULT (N''),
[_LE3_X19] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LE3_X19] DEFAULT (N''),
[_LE3_X4] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LE3_X4] DEFAULT (N''),
[_CX_CC_TRK1_PROFILE_CODE] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CC_TRK1_PROFILE_CODE] DEFAULT (N''),
[_CD3_X11] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CD3_X11] DEFAULT (N''),
[_LE3_X12] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LE3_X12] DEFAULT (N''),
[_CD3_X15] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CD3_X15] DEFAULT (N''),
[_NEWHUD2_X2273] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2273] DEFAULT (N''),
[_POPT_X244] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X244] DEFAULT (N''),
[_NEWHUD2_X82] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X82] DEFAULT (N''),
[_NEWHUD2_X3890] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3890] DEFAULT (N''),
[_NEWHUD2_X4385] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X4385] DEFAULT (N''),
[_NEWHUD2_X854] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X854] DEFAULT (N''),
[_NEWHUD2_X76] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X76] DEFAULT (N''),
[_NEWHUD2_X3758] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3758] DEFAULT (N''),
[_NEWHUD2_X4286] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X4286] DEFAULT (N'')
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[ti_LOANXDB_S_10_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_10]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF NOT EXISTS( SELECT 1 FROM emdbuser.LoanSummary ls JOIN inserted i ON i.XRefID = ls.XRefID)
	BEGIN

		INSERT INTO emdbuser.LoanSummary([Guid]
										,[LoanNumber]
										,[LoanFolder] 
										,[LoanName]
										,[Status]
										,[loanStatus]
										,[RateLockStatus]
										,[RateIsLocked]
										,[Investor]
										,[Broker]
										,[XRefID]
										,LastModified
										,LoanProcessorId
										,LoanType
										,HazardInsuranceVendor)
		SELECT NEWID()
			  ,''
			  ,''
			  ,NEWID()
			  ,'A'
			  ,''
			  ,''
			  ,''
			  ,''
			  ,''
			  ,XRefID
			  ,GETDATE()
			  ,LoanTeamMember_UserID_LoanCoordinator
			  ,_1172
			  ,_L252
		FROM inserted i
	END
	ELSE

		UPDATE ls
		SET  LoanProcessorId = i.LoanTeamMember_UserID_LoanCoordinator
			,LoanType = i._1172
			,HazardInsuranceVendor = i._L252
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[tu_LOANXDB_S_10_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_10]
   AFTER UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF (UPDATE(LoanTeamMember_UserID_LoanCoordinator) OR UPDATE(_1172) OR UPDATE(_L252))

		UPDATE ls
		SET  LoanProcessorId = i.LoanTeamMember_UserID_LoanCoordinator
			,LoanType = i._1172
			,HazardInsuranceVendor = i._L252
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
ALTER TABLE [emdbuser].[LOANXDB_S_10] ADD CONSTRAINT [PK_LOANXDB_S_10_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_10__65_P2_Includes] ON [emdbuser].[LOANXDB_S_10] ([_65_P2]) INCLUDE ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_10_LoanTeamMember_UserID_MortgageConsultant_Includes] ON [emdbuser].[LOANXDB_S_10] ([LoanTeamMember_UserID_MortgageConsultant]) INCLUDE ([_1172], [LoanTeamMember_Name_MortgageConsultant], [XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_10_CHILHQSQLDB_rs_BasicData_adalparams1_03] ON [emdbuser].[LOANXDB_S_10] ([XrefId]) INCLUDE ([_1172], [_CX_LEADSOURCE]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
