CREATE TABLE [emdbuser].[LOANXDB_S_06]
(
[XrefId] [int] NOT NULL,
[_CX_PREVINVEST4_10] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PREVINVEST4_10] DEFAULT (N''),
[_CX_SECCOMMIT5_10] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCOMMIT5_10] DEFAULT (N''),
[_CX_SECCOMMIT4_10] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCOMMIT4_10] DEFAULT (N''),
[_CX_SECCOMMIT3_10] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCOMMIT3_10] DEFAULT (N''),
[_CX_SECCOMMIT_10] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECCOMMIT_10] DEFAULT (N''),
[_SYS_X550] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X550] DEFAULT (N''),
[_SYS_X555] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X555] DEFAULT (N''),
[_SYS_X561] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X561] DEFAULT (N''),
[_SYS_X562] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X562] DEFAULT (N''),
[_SYS_X563] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X563] DEFAULT (N''),
[_SYS_X564] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X564] DEFAULT (N''),
[_SYS_X565] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X565] DEFAULT (N''),
[_SYS_X566] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X566] DEFAULT (N''),
[_SYS_X579] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X579] DEFAULT (N''),
[_2971] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2971] DEFAULT (N''),
[_CX_PREVINVEST5_10] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PREVINVEST5_10] DEFAULT (N''),
[LOCKRATE_2148] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_2148] DEFAULT (N''),
[_CX_HPMLMISC_16] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_HPMLMISC_16] DEFAULT (N''),
[_REQUEST_X6] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_REQUEST_X6] DEFAULT (N''),
[_1753] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1753] DEFAULT (N''),
[_109] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_109] DEFAULT (N''),
[_2363] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2363] DEFAULT (N''),
[_VEND_X22] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X22] DEFAULT (N''),
[_VEND_X54] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X54] DEFAULT (N''),
[_VEND_X84] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X84] DEFAULT (N''),
[_89] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_89] DEFAULT (N''),
[_620] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_620] DEFAULT (N''),
[_VEND_X156] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X156] DEFAULT (N''),
[_VEND_X146] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X146] DEFAULT (N''),
[_VEND_X164] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X164] DEFAULT (N''),
[_VEND_X162] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X162] DEFAULT (N''),
[_VEND_X160] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X160] DEFAULT (N''),
[_VEND_X112] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X112] DEFAULT (N''),
[_VEND_X117] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X117] DEFAULT (N''),
[_622] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_622] DEFAULT (N''),
[_VEND_X158] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X158] DEFAULT (N''),
[_VEND_X148] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X148] DEFAULT (N''),
[_VEND_X163] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X163] DEFAULT (N''),
[_VEND_X118] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X118] DEFAULT (N''),
[_VEND_X134] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X134] DEFAULT (N''),
[_VEND_X135] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X135] DEFAULT (N''),
[_VEND_X165] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X165] DEFAULT (N''),
[_VEND_X220] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X220] DEFAULT (N''),
[_VEND_X157] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X157] DEFAULT (N''),
[_VEND_X147] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X147] DEFAULT (N''),
[_VEND_X137] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X137] DEFAULT (N''),
[_VEND_X145] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X145] DEFAULT (N''),
[_621] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_621] DEFAULT (N''),
[_VEND_X115] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X115] DEFAULT (N''),
[_VEND_X113] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X113] DEFAULT (N''),
[_1244] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1244] DEFAULT (N''),
[_VEND_X159] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X159] DEFAULT (N''),
[_1246] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1246] DEFAULT (N''),
[_1264] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1264] DEFAULT (N''),
[_703] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_703] DEFAULT (N''),
[_1249] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1249] DEFAULT (N''),
[_625] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_625] DEFAULT (N''),
[_1011] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1011] DEFAULT (N''),
[_616] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_616] DEFAULT (N''),
[_416] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_416] DEFAULT (N''),
[_56] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_56] DEFAULT (N''),
[_711] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_711] DEFAULT (N''),
[_702] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_702] DEFAULT (N''),
[_1252] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1252] DEFAULT (N''),
[_629] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_629] DEFAULT (N''),
[_1409] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1409] DEFAULT (N''),
[_624] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_624] DEFAULT (N''),
[_1823] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1823] DEFAULT (N''),
[_709] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_709] DEFAULT (N''),
[_313] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_313] DEFAULT (N''),
[_615] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_615] DEFAULT (N''),
[_627] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_627] DEFAULT (N''),
[_638] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_638] DEFAULT (N''),
[_1175] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1175] DEFAULT (N''),
[_1243] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1243] DEFAULT (N''),
[_611] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_611] DEFAULT (N''),
[_1245] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1245] DEFAULT (N''),
[_1247] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1247] DEFAULT (N''),
[_628] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_628] DEFAULT (N''),
[_1408] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1408] DEFAULT (N''),
[_90] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_90] DEFAULT (N''),
[_1417] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1417] DEFAULT (N''),
[_1419] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1419] DEFAULT (N''),
[_1418] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1418] DEFAULT (N''),
[_305] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_305] DEFAULT (N''),
[_33] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_33] DEFAULT (N''),
[_24] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_24] DEFAULT (N''),
[_30] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_30] DEFAULT (N''),
[_1522] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1522] DEFAULT (N''),
[_233] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_233] DEFAULT (N''),
[_1521] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1521] DEFAULT (N''),
[_1520] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1520] DEFAULT (N''),
[_1301] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1301] DEFAULT (N''),
[_186] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_186] DEFAULT (N''),
[_168] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_168] DEFAULT (N''),
[_994] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_994] DEFAULT (N''),
[_84] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_84] DEFAULT (N''),
[_31] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_31] DEFAULT (N''),
[_53] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_53] DEFAULT (N''),
[_FE0102] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0102] DEFAULT (N''),
[_FE0202] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0202] DEFAULT (N''),
[_FE0105] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0105] DEFAULT (N''),
[_FE0205] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0205] DEFAULT (N''),
[_1452] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1452] DEFAULT (N''),
[_1063] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1063] DEFAULT (N''),
[_205] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_205] DEFAULT (N''),
[_85] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_85] DEFAULT (N''),
[_86] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_86] DEFAULT (N''),
[_54] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_54] DEFAULT (N''),
[_FE0110] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0110] DEFAULT (N''),
[_FE0210] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0210] DEFAULT (N''),
[_1480] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1480] DEFAULT (N''),
[_17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_17] DEFAULT (N''),
[_1450] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1450] DEFAULT (N''),
[_1415] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1415] DEFAULT (N''),
[_1414] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1414] DEFAULT (N''),
[_FE0107] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0107] DEFAULT (N''),
[_FE0106] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0106] DEFAULT (N''),
[_FE0206] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0206] DEFAULT (N''),
[_FE0207] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0207] DEFAULT (N''),
[_2029] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2029] DEFAULT (N''),
[_CX_COMPAREOVERCITY_10] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREOVERCITY_10] DEFAULT (N''),
[_CX_COMPAREOVERADDR_10] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREOVERADDR_10] DEFAULT (N''),
[_CX_APPRORDERCOCITY_4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRORDERCOCITY_4] DEFAULT (N''),
[_CX_APPRORDERCOST_4] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRORDERCOST_4] DEFAULT (N''),
[_CX_TAXSMART_10] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_TAXSMART_10] DEFAULT (N''),
[_CX_APPRTYPE_10] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRTYPE_10] DEFAULT (N''),
[_NEWHUD_X578] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X578] DEFAULT (N''),
[_NEWHUD_X625] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X625] DEFAULT (N''),
[_NEWHUD_X579] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X579] DEFAULT (N''),
[_NEWHUD_X357] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X357] DEFAULT (N''),
[_NEWHUD_X110] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X110] DEFAULT (N''),
[_NEWHUD_X111] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X111] DEFAULT (N''),
[_NEWHUD_X339] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X339] DEFAULT (N''),
[_NEWHUD_X690] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X690] DEFAULT (N''),
[_NEWHUD_X8] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X8] DEFAULT (N''),
[_NEWHUD_X276] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X276] DEFAULT (N''),
[_NEWHUD_X580] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X580] DEFAULT (N''),
[_NEWHUD_X120] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X120] DEFAULT (N''),
[_NEWHUD_X354] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X354] DEFAULT (N''),
[_NEWHUD_X576] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X576] DEFAULT (N''),
[_NEWHUD_X684] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X684] DEFAULT (N''),
[_NEWHUD_X372] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X372] DEFAULT (N''),
[_CX_CLSVOEVERIFIED] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSVOEVERIFIED] DEFAULT (N''),
[_CX_PROBDISSUBDOC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBDISSUBDOC] DEFAULT (N''),
[_CX_UWASSISTANT] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWASSISTANT] DEFAULT (N''),
[_CX_UWSUB24HRBRK] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWSUB24HRBRK] DEFAULT (N''),
[_CX_UWFASTTRACK] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWFASTTRACK] DEFAULT (N''),
[_CX_PROBDISPCLSDOC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBDISPCLSDOC] DEFAULT (N''),
[_CX_PROBDISPCONDDOC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBDISPCONDDOC] DEFAULT (N''),
[_1612] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1612] DEFAULT (N''),
[_CX_LPMI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LPMI] DEFAULT (N''),
[_HMDA_X15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_HMDA_X15] DEFAULT (N''),
[_HMDA_X24] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_HMDA_X24] DEFAULT (N''),
[_CX_PREAPRVL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PREAPRVL] DEFAULT (N''),
[_CX_SHPCHK_1] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHPCHK_1] DEFAULT (N''),
[_1416] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1416] DEFAULT (N''),
[_1519] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1519] DEFAULT (N''),
[_619] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_619] DEFAULT (N''),
[_626] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_626] DEFAULT (N''),
[_701] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_701] DEFAULT (N''),
[_708] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_708] DEFAULT (N''),
[_FE0204] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0204] DEFAULT (N''),
[_FE0104] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0104] DEFAULT (N''),
[_660] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_660] DEFAULT (N''),
[_661] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_661] DEFAULT (N''),
[_1290] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1290] DEFAULT (N''),
[_NMLS_X10] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NMLS_X10] DEFAULT (N''),
[_CX_INSQTE_EZLYNX] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSQTE_EZLYNX] DEFAULT (N''),
[_CX_LM_TRAININGOPP] [varchar] (3000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LM_TRAININGOPP] DEFAULT (N''),
[_CX_CONSULTANT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CONSULTANT] DEFAULT (N''),
[_2004] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2004] DEFAULT (N''),
[_1188] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1188] DEFAULT (N''),
[_CX_CONTRACTOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CONTRACTOR] DEFAULT (N''),
[_3502] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3502] DEFAULT (N''),
[_2178] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2178] DEFAULT (N''),
[_CX_AREGIFTFUNDSDOCUMENTED] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_AREGIFTFUNDSDOCUMENTED] DEFAULT (N''),
[_CX_DIVORCEDECREESREQUIRED] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_DIVORCEDECREESREQUIRED] DEFAULT (N''),
[_CX_ISBUSPAIDDEBTEXCLUDED] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ISBUSPAIDDEBTEXCLUDED] DEFAULT (N''),
[_CX_ISRENTALINCOMEVERIFREQD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ISRENTALINCOMEVERIFREQD] DEFAULT (N''),
[_CX_REPULL_CRT_OF_ELIGIBILITY] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_REPULL_CRT_OF_ELIGIBILITY] DEFAULT (N''),
[_CX_DEPRESINCUSED] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_DEPRESINCUSED] DEFAULT (N''),
[_CX_LIQUIDATIONOFASSETS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LIQUIDATIONOFASSETS] DEFAULT (N''),
[_CX_OVERRIDE_UW] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_OVERRIDE_UW] DEFAULT (N''),
[_CX_UWC_SELECTED_UNDERWRITER] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWC_SELECTED_UNDERWRITER] DEFAULT (N''),
[_POPT_X300] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X300] DEFAULT (N''),
[_POPT_X234] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X234] DEFAULT (N''),
[_POPT_X183] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X183] DEFAULT (N''),
[_NEWHUD_X1395] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1395] DEFAULT (N''),
[_POPT_X216] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X216] DEFAULT (N''),
[_POPT_X231] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X231] DEFAULT (N''),
[_POPT_X222] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X222] DEFAULT (N''),
[_POPT_X341] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X341] DEFAULT (N''),
[_POPT_X296] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X296] DEFAULT (N''),
[_POPT_X348] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X348] DEFAULT (N''),
[_POPT_X338] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X338] DEFAULT (N''),
[_POPT_X160] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X160] DEFAULT (N''),
[_POPT_X337] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X337] DEFAULT (N''),
[_POPT_X343] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X343] DEFAULT (N''),
[_DISCLOSURE_X1090] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DISCLOSURE_X1090] DEFAULT (N''),
[_DISCLOSURE_X1091] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DISCLOSURE_X1091] DEFAULT (N''),
[_DISCLOSURE_X1092] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DISCLOSURE_X1092] DEFAULT (N''),
[_DISCLOSURE_X1093] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DISCLOSURE_X1093] DEFAULT (N''),
[_POPT_X214] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X214] DEFAULT (N''),
[_POPT_X308] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X308] DEFAULT (N''),
[_POPT_X178] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X178] DEFAULT (N''),
[_POPT_X180] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X180] DEFAULT (N''),
[_POPT_X294] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X294] DEFAULT (N''),
[_POPT_X166] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X166] DEFAULT (N''),
[_POPT_X176] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X176] DEFAULT (N''),
[_POPT_X302] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X302] DEFAULT (N''),
[_POPT_X188] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X188] DEFAULT (N''),
[_POPT_X198] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X198] DEFAULT (N''),
[_POPT_X196] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X196] DEFAULT (N''),
[_POPT_X298] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X298] DEFAULT (N''),
[_POPT_X313] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X313] DEFAULT (N''),
[_POPT_X192] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X192] DEFAULT (N''),
[_POPT_X226] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X226] DEFAULT (N''),
[_POPT_X206] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X206] DEFAULT (N''),
[_POPT_X312] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X312] DEFAULT (N''),
[_POPT_X305] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X305] DEFAULT (N''),
[_POPT_X315] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X315] DEFAULT (N''),
[_POPT_X208] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X208] DEFAULT (N''),
[_CX_RUSH_BUNDLES] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RUSH_BUNDLES] DEFAULT (N''),
[_POPT_X202] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X202] DEFAULT (N''),
[_POPT_X311] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X311] DEFAULT (N''),
[_POPT_X224] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X224] DEFAULT (N''),
[_POPT_X194] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X194] DEFAULT (N''),
[_POPT_X342] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X342] DEFAULT (N''),
[_POPT_X232] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X232] DEFAULT (N''),
[_POPT_X215] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X215] DEFAULT (N''),
[_POPT_X309] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X309] DEFAULT (N''),
[_POPT_X307] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X307] DEFAULT (N''),
[_POPT_X221] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X221] DEFAULT (N''),
[_POPT_X295] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X295] DEFAULT (N''),
[_POPT_X165] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X165] DEFAULT (N''),
[_POPT_X175] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X175] DEFAULT (N''),
[_POPT_X310] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X310] DEFAULT (N''),
[_POPT_X199] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X199] DEFAULT (N''),
[_POPT_X161] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X161] DEFAULT (N''),
[_POPT_X171] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X171] DEFAULT (N''),
[_POPT_X207] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X207] DEFAULT (N''),
[_POPT_X217] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X217] DEFAULT (N''),
[_POPT_X223] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X223] DEFAULT (N''),
[_POPT_X233] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X233] DEFAULT (N''),
[_POPT_X201] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X201] DEFAULT (N''),
[_POPT_X297] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X297] DEFAULT (N''),
[_POPT_X181] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X181] DEFAULT (N''),
[_POPT_X191] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_POPT_X191] DEFAULT (N'')
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[ti_LOANXDB_S_06_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_06]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF NOT EXISTS( SELECT 1 FROM emdbuser.LoanSummary ls JOIN inserted i ON i.XRefID = ls.XRefID)
	BEGIN

		INSERT INTO emdbuser.LoanSummary([Guid]
										,[LoanNumber]
										,[LoanFolder] 
										,[LoanName]
										,[Status]
										,[loanStatus]
										,[RateLockStatus]
										,[RateIsLocked]
										,[Investor]
										,[Broker]
										,[XRefID]
										,LastModified
										,Lender
										,CreditVendor)
		SELECT NEWID()
			  ,''
			  ,''
			  ,NEWID()
			  ,'A'
			  ,''
			  ,''
			  ,''
			  ,''
			  ,''
			  ,XRefID
			  ,GETDATE()
			  ,_1264
			  ,_624
		FROM inserted i
	END
	ELSE

		UPDATE ls
		SET  Lender = i._1264
			,CreditVendor = i._624
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[tu_LOANXDB_S_06_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_06]
   AFTER UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF (UPDATE(_1264) OR UPDATE(_624))

		UPDATE ls
		SET  Lender = i._1264
			,CreditVendor = i._624
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
ALTER TABLE [emdbuser].[LOANXDB_S_06] ADD CONSTRAINT [PK_LOANXDB_S_06_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_06__1612_FE0102_FE0107_FE0110_54] ON [emdbuser].[LOANXDB_S_06] ([_1612], [_FE0102], [_FE0107], [_FE0110], [_54]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
