CREATE TABLE [emdbuser].[LOANXDB_S_03]
(
[XrefId] [int] NOT NULL,
[_CX_COMPARELIEN_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPARELIEN_2] DEFAULT (N''),
[_CX_ACCTCHECK3_3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCTCHECK3_3] DEFAULT (N''),
[_CX_INSURNOTE1_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_INSURNOTE1_1] DEFAULT (N''),
[_CUST71FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST71FV] DEFAULT (N'//'),
[_CX_UWCLEANMC_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWCLEANMC_1] DEFAULT (N''),
[_CX_FUNDASSOCINVCD_2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDASSOCINVCD_2] DEFAULT (N''),
[_CX_CREDITCNUMBER_1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CREDITCNUMBER_1] DEFAULT (N''),
[_2316] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2316] DEFAULT (N''),
[_CUST66FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST66FV] DEFAULT (N''),
[_CX_CCARDEXPIRE_1] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CCARDEXPIRE_1] DEFAULT (N'/'),
[_VEND_X276] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X276] DEFAULT (N''),
[_478] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_478] DEFAULT (N''),
[_15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_15] DEFAULT (N''),
[_CX_FUNDASSOCPROD_2] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDASSOCPROD_2] DEFAULT (N''),
[LOCKRATE_1401] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_1401] DEFAULT (N''),
[_1946] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1946] DEFAULT (N''),
[_FR0108] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0108] DEFAULT (N''),
[_CX_MCNAME_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_MCNAME_1] DEFAULT (N''),
[Log_MS_DateTime_Resubmittal] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_DateTime_Resubmittal] DEFAULT (N'//'),
[_CX_NOTSOLD_3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_NOTSOLD_3] DEFAULT (N''),
[_CUST67FV] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST67FV] DEFAULT (N''),
[_614] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_614] DEFAULT (N''),
[PreviousTeamMember] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFPreviousTeamMember] DEFAULT (N''),
[_931] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_931] DEFAULT (N''),
[_VEND_X200] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X200] DEFAULT (N''),
[_UWC_ALL] [varchar] (4096) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_UWC_ALL] DEFAULT (N''),
[_369] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_369] DEFAULT (N''),
[_CX_UWCLEANLC_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWCLEANLC_1] DEFAULT (N''),
[_CX_COMPAREFICO_3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREFICO_3] DEFAULT (N''),
[_65] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_65] DEFAULT (N''),
[_CX_CLSCOORD_1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSCOORD_1] DEFAULT (N''),
[LOCKRATE_CURRENTDATETIME] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_CURRENTDATETIME] DEFAULT (N''),
[_470] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_470] DEFAULT (N''),
[_CX_COMPAREOVERPROP_2] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREOVERPROP_2] DEFAULT (N''),
[_417] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_417] DEFAULT (N''),
[_2052] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2052] DEFAULT (N''),
[_477] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_477] DEFAULT (N''),
[_8] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_8] DEFAULT (N''),
[_CX_BRKRINVESTOR_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_BRKRINVESTOR_3] DEFAULT (N''),
[_CX_BRKRPROGRAM_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_BRKRPROGRAM_3] DEFAULT (N''),
[_CX_COMPAREZIP_3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREZIP_3] DEFAULT (N''),
[_CX_COMPAREADDR_3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPAREADDR_3] DEFAULT (N''),
[_CX_SECAUSNUMB_4] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECAUSNUMB_4] DEFAULT (N''),
[_CX_FUND_3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUND_3] DEFAULT (N''),
[_CX_FINALOCODE_4] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FINALOCODE_4] DEFAULT (N''),
[_CX_COMPARECITYST_3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COMPARECITYST_3] DEFAULT (N''),
[_CX_SHIPNOTES2_4] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHIPNOTES2_4] DEFAULT (N''),
[_CX_SHIPNOTES3_4] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHIPNOTES3_4] DEFAULT (N''),
[_299] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_299] DEFAULT (N''),
[LoanTeamMember_Phone_LoanOfficer] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLoanTeamMember_Phone_LoanOfficer] DEFAULT (N''),
[LoanTeamMember_Name_LoanOfficer] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLoanTeamMember_Name_LoanOfficer] DEFAULT (N''),
[_2002] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2002] DEFAULT (N''),
[_CUST21FV] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CUST21FV] DEFAULT (N'//'),
[_CX_SECONDMI_4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECONDMI_4] DEFAULT (N''),
[_CX_APPRCOMMENTS_4] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRCOMMENTS_4] DEFAULT (N''),
[_CX_APPRORDERCO_4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRORDERCO_4] DEFAULT (N''),
[_CX_FINALAUS_4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FINALAUS_4] DEFAULT (N''),
[_187] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_187] DEFAULT (N''),
[_1822] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1822] DEFAULT (N''),
[_CX_SHIPSEVRPKGSHIPPER_4] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHIPSEVRPKGSHIPPER_4] DEFAULT (N''),
[_CX_SHIPCOLLSHIPPER_4] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHIPCOLLSHIPPER_4] DEFAULT (N''),
[_VEND_X150] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X150] DEFAULT (N''),
[_VEND_X140] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X140] DEFAULT (N''),
[_VEND_X153] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X153] DEFAULT (N''),
[_VEND_X133] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X133] DEFAULT (N''),
[_2358] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2358] DEFAULT (N''),
[_VEND_X151] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X151] DEFAULT (N''),
[_VEND_X142] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X142] DEFAULT (N''),
[_675] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_675] DEFAULT (N''),
[_1051] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1051] DEFAULT (N''),
[_CX_SHIPNOTES1_4] [varchar] (275) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHIPNOTES1_4] DEFAULT (N''),
[_420] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_420] DEFAULT (N''),
[_CX_SECEXTEND2] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECEXTEND2] DEFAULT (N''),
[_CX_SECEXTEND] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SECEXTEND] DEFAULT (N''),
[_CX_CLSSENDTOSHIPT] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSSENDTOSHIPT] DEFAULT (N''),
[_CX_ESTSCHEDT] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ESTSCHEDT] DEFAULT (N''),
[_CX_ESTCLST] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ESTCLST] DEFAULT (N''),
[_SYS_X53] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X53] DEFAULT (N''),
[_SYS_X470] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X470] DEFAULT (N''),
[_SYS_X430] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X430] DEFAULT (N''),
[_SYS_X431] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X431] DEFAULT (N''),
[_SYS_X432] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X432] DEFAULT (N''),
[_SYS_X433] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X433] DEFAULT (N''),
[_SYS_X434] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X434] DEFAULT (N''),
[_SYS_X435] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X435] DEFAULT (N''),
[_SYS_X436] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X436] DEFAULT (N''),
[_SYS_X437] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X437] DEFAULT (N''),
[_SYS_X438] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X438] DEFAULT (N''),
[_SYS_X485] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X485] DEFAULT (N''),
[_SYS_X486] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X486] DEFAULT (N''),
[_SYS_X487] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X487] DEFAULT (N''),
[_SYS_X489] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X489] DEFAULT (N''),
[_CX_ESTFUNDT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ESTFUNDT] DEFAULT (N''),
[_SYS_X46] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X46] DEFAULT (N''),
[_SYS_X42] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X42] DEFAULT (N''),
[_SYS_X512] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X512] DEFAULT (N''),
[_SYS_X513] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X513] DEFAULT (N''),
[_SYS_X514] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X514] DEFAULT (N''),
[_SYS_X490] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X490] DEFAULT (N''),
[_SYS_X494] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X494] DEFAULT (N''),
[_SYS_X495] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X495] DEFAULT (N''),
[_SYS_X497] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X497] DEFAULT (N''),
[_SYS_X47] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X47] DEFAULT (N''),
[_SYS_X54] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X54] DEFAULT (N''),
[_SYS_X410] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X410] DEFAULT (N''),
[_SYS_X411] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X411] DEFAULT (N''),
[_SYS_X412] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X412] DEFAULT (N''),
[_SYS_X414] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X414] DEFAULT (N''),
[_SYS_X416] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X416] DEFAULT (N''),
[_SYS_X417] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X417] DEFAULT (N''),
[_SYS_X418] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X418] DEFAULT (N''),
[_SYS_X44] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X44] DEFAULT (N''),
[_SYS_X52] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X52] DEFAULT (N''),
[_SYS_X420] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X420] DEFAULT (N''),
[_SYS_X421] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X421] DEFAULT (N''),
[_SYS_X422] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X422] DEFAULT (N''),
[_SYS_X500] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X500] DEFAULT (N''),
[_SYS_X266] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X266] DEFAULT (N''),
[_SYS_X270] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X270] DEFAULT (N''),
[_SYS_X272] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X272] DEFAULT (N''),
[_SYS_X262] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X262] DEFAULT (N''),
[_NEWHUD_X230] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X230] DEFAULT (N''),
[_2243] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2243] DEFAULT (N''),
[_2245] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2245] DEFAULT (N''),
[_2247] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2247] DEFAULT (N''),
[_2249] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2249] DEFAULT (N''),
[_SERVICE_X11] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X11] DEFAULT (N''),
[_SERVICE_X5] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X5] DEFAULT (N''),
[_SERVICE_X6] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X6] DEFAULT (N''),
[_SERVICE_X8] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X8] DEFAULT (N''),
[_SERVICE_X7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X7] DEFAULT (N''),
[_SERVICE_X1] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X1] DEFAULT (N''),
[_SERVICE_X2] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X2] DEFAULT (N''),
[_SERVICE_X3] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X3] DEFAULT (N''),
[_SERVICE_X4] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SERVICE_X4] DEFAULT (N''),
[_SYS_X1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X1] DEFAULT (N''),
[_1405] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1405] DEFAULT (N''),
[_VEND_X129] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X129] DEFAULT (N''),
[_VEND_X124] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X124] DEFAULT (N''),
[_VEND_X499] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X499] DEFAULT (N''),
[_VEND_X128] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X128] DEFAULT (N''),
[_VEND_X125] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X125] DEFAULT (N''),
[_VEND_X498] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X498] DEFAULT (N''),
[_VEND_X126] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X126] DEFAULT (N''),
[_VEND_X123] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X123] DEFAULT (N''),
[_CX_BKTFEE_1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_BKTFEE_1] DEFAULT (N''),
[_NEWHUD_X1173] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1173] DEFAULT (N''),
[_NEWHUD_X1171] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1171] DEFAULT (N''),
[_NEWHUD_X1167] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1167] DEFAULT (N''),
[_NEWHUD_X1178] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1178] DEFAULT (N''),
[_NEWHUD_X1169] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1169] DEFAULT (N''),
[_NEWHUD_X1190] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1190] DEFAULT (N''),
[_NEWHUD_X1186] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1186] DEFAULT (N''),
[_NEWHUD_X1182] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1182] DEFAULT (N''),
[_NEWHUD_X1139] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD_X1139] DEFAULT (N''),
[_CX_UWREQMI] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWREQMI] DEFAULT (N''),
[_CX_NUMUWCONDITION] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_NUMUWCONDITION] DEFAULT (N''),
[_GUID] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_GUID] DEFAULT (N''),
[_479] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_479] DEFAULT (N''),
[_1397] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1397] DEFAULT (N''),
[_CX_UWNUMCNDOREVD] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWNUMCNDOREVD] DEFAULT (N''),
[_CX_APPRTYPE3_4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRTYPE3_4] DEFAULT (N''),
[_CX_APPRORDERCO3_4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRORDERCO3_4] DEFAULT (N''),
[_CX_CHKPURPOTHER_1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKPURPOTHER_1] DEFAULT (N''),
[_CX_CHKREQPAYEE_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQPAYEE_2] DEFAULT (N''),
[_CX_CHKPURPOTHER_2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKPURPOTHER_2] DEFAULT (N''),
[_CX_CHKRQSTPURP_1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKRQSTPURP_1] DEFAULT (N''),
[_CX_CHKRQSTPURP_3] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKRQSTPURP_3] DEFAULT (N''),
[_CX_CHKRQSTPURP_2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKRQSTPURP_2] DEFAULT (N''),
[_CX_CHKREQPAYEE_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQPAYEE_3] DEFAULT (N''),
[_CX_CHKREQPAYEE_1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQPAYEE_1] DEFAULT (N''),
[_CX_CHKPURPOTHER_3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKPURPOTHER_3] DEFAULT (N''),
[_CX_CHKDELIVOPT_3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKDELIVOPT_3] DEFAULT (N''),
[_CX_CHKDELIVOPT_2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKDELIVOPT_2] DEFAULT (N''),
[_CX_CHKDELIVOPT_1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKDELIVOPT_1] DEFAULT (N''),
[_2400] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2400] DEFAULT (N''),
[_995] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_995] DEFAULT (N''),
[_1659] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1659] DEFAULT (N''),
[_965] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_965] DEFAULT (N''),
[_CX_PROPTAXSTATE_1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROPTAXSTATE_1] DEFAULT (N''),
[_CX_UWRECOND] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWRECOND] DEFAULT (N''),
[_FR0204] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FR0204] DEFAULT (N''),
[_1894] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1894] DEFAULT (N''),
[_CX_COPYLOBPS] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COPYLOBPS] DEFAULT (N''),
[_3046] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_3046] DEFAULT (N''),
[_CX_EMPLOAN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_EMPLOAN] DEFAULT (N''),
[_1853] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1853] DEFAULT (N''),
[_FL0518] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0518] DEFAULT (N''),
[_FL0418] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0418] DEFAULT (N''),
[_FL0318] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0318] DEFAULT (N''),
[_FL0718] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0718] DEFAULT (N''),
[_FL0818] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0818] DEFAULT (N''),
[_FL0618] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0618] DEFAULT (N''),
[_FL0118] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0118] DEFAULT (N''),
[_FL0218] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0218] DEFAULT (N''),
[_FL0918] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0918] DEFAULT (N''),
[_CX_RUSH_UW_CMNTS_APRVL_3] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RUSH_UW_CMNTS_APRVL_3] DEFAULT (N''),
[_CD5_X67] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CD5_X67] DEFAULT (N''),
[_CX_CHKREQTIME_3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CHKREQTIME_3] DEFAULT (N''),
[_NEWHUD2_X2603] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2603] DEFAULT (N''),
[_NEWHUD2_X293] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X293] DEFAULT (N''),
[_NEWHUD2_X425] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X425] DEFAULT (N''),
[_NEWHUD2_X458] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X458] DEFAULT (N''),
[_NEWHUD2_X3989] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3989] DEFAULT (N''),
[_NEWHUD2_X3956] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3956] DEFAULT (N''),
[_NEWHUD2_X3329] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3329] DEFAULT (N''),
[_NEWHUD2_X2471] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2471] DEFAULT (N''),
[_NEWHUD2_X3791] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3791] DEFAULT (N''),
[_NEWHUD2_X1943] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X1943] DEFAULT (N''),
[_NEWHUD2_X85] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X85] DEFAULT (N''),
[_NEWHUD2_X1349] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X1349] DEFAULT (N''),
[_NEWHUD2_X1118] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X1118] DEFAULT (N''),
[_NEWHUD2_X590] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X590] DEFAULT (N''),
[_NEWHUD2_X2933] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2933] DEFAULT (N''),
[_NEWHUD2_X227] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X227] DEFAULT (N''),
[_NEWHUD2_X2999] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2999] DEFAULT (N''),
[_NEWHUD2_X2339] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2339] DEFAULT (N''),
[_NEWHUD2_X821] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X821] DEFAULT (N''),
[_NEWHUD2_X3131] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3131] DEFAULT (N''),
[_NEWHUD2_X3032] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X3032] DEFAULT (N''),
[_NEWHUD2_X73] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X73] DEFAULT (N''),
[_NEWHUD2_X359] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X359] DEFAULT (N''),
[_NEWHUD2_X1877] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X1877] DEFAULT (N''),
[_NEWHUD2_X491] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X491] DEFAULT (N'')
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[ti_LOANXDB_S_03_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_03]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF NOT EXISTS( SELECT 1 FROM emdbuser.LoanSummary ls JOIN inserted i ON i.XRefID = ls.XRefID)
	BEGIN

		INSERT INTO emdbuser.LoanSummary([Guid]
										,[LoanNumber]
										,[LoanFolder] 
										,[LoanName]
										,[Status]
										,[loanStatus]
										,[RateLockStatus]
										,[RateIsLocked]
										,[Investor]
										,[Broker]
										,[XRefID]
										,LastModified
										,[Zip]
										,[ReferralSource]
										,[CoBorrowerSex]
										--,LienPosition  --This is calculated based on the value of [SecondMortgage]
										,[SecondMortgage]
										,[ISStatus]
										,[LoanOfficerName]
)
		SELECT _guid
			  ,''
			  ,''
			  ,NEWID()
			  ,'A'
			  ,''
			  ,''
			  ,''
			  ,''
			  ,''
			  ,XRefID
			  ,GETDATE()
			  ,_15
			  ,_1822
			  ,_478
			  ,CASE WHEN _420 = 'Second Lien' THEN 'Y' ELSE 'N' END
			  ,CAST(CASE WHEN ISNULL(_SERVICE_X8,'') = '' THEN 'Not Servicing' ELSE _SERVICE_X8 END AS VARCHAR(20))
			  ,LoanTeamMember_Name_LoanOfficer
		FROM inserted i
	END
	ELSE

		UPDATE ls
		SET  Zip = i._15
			,Guid = i._GUID
			,AppraisalVendor = i._CX_APPRORDERCO_4
			,ReferralSource = i._1822
			,CoBorrowerSex = i._478
			,SecondMortgage = CASE WHEN i._420 = 'Second Lien' THEN 'Y' ELSE 'N' END
			,ISStatus = CAST(CASE WHEN ISNULL(i._SERVICE_X8,'') = '' THEN 'Not Servicing' ELSE i._SERVICE_X8 END AS VARCHAR(20))
			,LoanOfficerName = i.LoanTeamMember_Name_LoanOfficer
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[tu_LOANXDB_S_03_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_03]
   AFTER UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF (UPDATE(_guid) OR UPDATE(XRefID) OR UPDATE(_15) OR UPDATE(_1822) OR UPDATE(_478) OR UPDATE(_SERVICE_X8) OR UPDATE(_420) OR UPDATE(LoanTeamMember_Name_LoanOfficer))

		UPDATE ls
		SET  Zip = i._15
			,Guid = i._GUID
			,ReferralSource = i._1822
			,CoBorrowerSex = i._478
			,SecondMortgage = CASE WHEN i._420 = 'Second Lien' THEN 'Y' ELSE 'N' END
			,ISStatus = CAST(CASE WHEN ISNULL(i._SERVICE_X8,'') = '' THEN 'Not Servicing' ELSE i._SERVICE_X8 END AS VARCHAR(20))
			,LoanOfficerName = i.LoanTeamMember_Name_LoanOfficer
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
ALTER TABLE [emdbuser].[LOANXDB_S_03] ADD CONSTRAINT [PK_LOANXDB_S_03_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_03__478] ON [emdbuser].[LOANXDB_S_03] ([_478]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_03_LoanService_02] ON [emdbuser].[LOANXDB_S_03] ([_65], [_FR0108]) WITH (FILLFACTOR=100, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_LOANXDB_S_03_CX_FINALOCODE_4] ON [emdbuser].[LOANXDB_S_03] ([_CX_FINALOCODE_4]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_03_LoanService_10] ON [emdbuser].[LOANXDB_S_03] ([XrefId]) INCLUDE ([_1051], [_15], [_1822], [_65], [_CX_FINALOCODE_4], [_SERVICE_X8], [LOCKRATE_1401]) WITH (FILLFACTOR=100, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_03_Warehouse_Secmktg_DailyLocks_01] ON [emdbuser].[LOANXDB_S_03] ([XrefId]) INCLUDE ([_420], [_CX_FINALOCODE_4], [_VEND_X200], [LOCKRATE_1401]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
