CREATE TABLE [emdbuser].[LOANXDB_S_18]
(
[XrefId] [int] NOT NULL,
[_CX_NOV_COMMENTS] [varchar] (2400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_NOV_COMMENTS] DEFAULT (N''),
[_CX_CLOSING_COMMENTS] [varchar] (750) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLOSING_COMMENTS] DEFAULT (N''),
[_CX_FUNDING_COMMENTS] [varchar] (750) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FUNDING_COMMENTS] DEFAULT (N''),
[_CX_ESCROW_CLOSEOUT_NOTES] [varchar] (800) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ESCROW_CLOSEOUT_NOTES] DEFAULT (N''),
[_CX_LM_CURRENT_SVC_STATUS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LM_CURRENT_SVC_STATUS] DEFAULT (N''),
[_CX_LM_RE_REASON] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LM_RE_REASON] DEFAULT (N''),
[_CX_LOSS_MIT_REP] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LOSS_MIT_REP] DEFAULT (N''),
[_CX_RELO_YN] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_RELO_YN] DEFAULT (N''),
[_2840] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2840] DEFAULT (N''),
[_BE0117] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BE0117] DEFAULT (N''),
[_FL0107] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FL0107] DEFAULT (N''),
[_DD0107] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0107] DEFAULT (N''),
[_CE0117] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0117] DEFAULT (N''),
[_DD0206] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DD0206] DEFAULT (N''),
[_CE0106] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CE0106] DEFAULT (N'')
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_S_18] ADD CONSTRAINT [PK_LOANXDB_S_18_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_18_LicensingLoanDetails_02] ON [emdbuser].[LOANXDB_S_18] ([XrefId]) INCLUDE ([_CE0106]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
