CREATE TABLE [emdbuser].[LOANXDB_S_04]
(
[XrefId] [int] NOT NULL,
[_CX_PROBLOANCMT_4] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBLOANCMT_4] DEFAULT (N''),
[_VEND_X144] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X144] DEFAULT (N''),
[_VEND_X139] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X139] DEFAULT (N''),
[_VEND_X141] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X141] DEFAULT (N''),
[_CX_SHIPNOTES4_5] [varchar] (225) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_SHIPNOTES4_5] DEFAULT (N''),
[_VEND_X152] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X152] DEFAULT (N''),
[Log_MS_DateTime_AssignedtoUW] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_DateTime_AssignedtoUW] DEFAULT (N'//'),
[Log_MS_DateTime_DecisionExpected] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_DateTime_DecisionExpected] DEFAULT (N'//'),
[Log_MS_DateTime_Approval] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_DateTime_Approval] DEFAULT (N'//'),
[Log_MS_DateTime_submittal] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_DateTime_submittal] DEFAULT (N'//'),
[_CX_UWMIPCT_5] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWMIPCT_5] DEFAULT (N''),
[_618] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_618] DEFAULT (N''),
[_52] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_52] DEFAULT (N''),
[_LOANFOLDER] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANFOLDER] DEFAULT (N''),
[_CX_ACCOKTOCHRG_5] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCOKTOCHRG_5] DEFAULT (N''),
[_CX_ACCCARDCITY_5] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCARDCITY_5] DEFAULT (N''),
[_CX_ACCCARDADD_5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCARDADD_5] DEFAULT (N''),
[_CX_ACCCARDTYPE_5] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCARDTYPE_5] DEFAULT (N''),
[_CX_ACCCARDST_5] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCARDST_5] DEFAULT (N''),
[_CX_ACCOKTOREV_5] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCOKTOREV_5] DEFAULT (N''),
[_CX_ACCCARDZIP_5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCARDZIP_5] DEFAULT (N''),
[_974] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_974] DEFAULT (N''),
[_2306] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2306] DEFAULT (N''),
[_1502] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1502] DEFAULT (N''),
[_2866] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2866] DEFAULT (N''),
[_2577] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2577] DEFAULT (N''),
[_2576] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2576] DEFAULT (N''),
[_2575] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2575] DEFAULT (N''),
[_HMDA_X13] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_HMDA_X13] DEFAULT (N''),
[_CASASRN_X13] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASASRN_X13] DEFAULT (N''),
[_1523] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1523] DEFAULT (N''),
[_1531] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1531] DEFAULT (N''),
[_CX_ISINVEXP_5] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ISINVEXP_5] DEFAULT (N''),
[_CX_ACCREV_5] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCREV_5] DEFAULT (N''),
[_CX_ACCCARDNAME_5] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCARDNAME_5] DEFAULT (N''),
[_CX_CCARDTRANS_5] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CCARDTRANS_5] DEFAULT (N''),
[_CX_ACCCHG_5] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACCCHG_5] DEFAULT (N''),
[_CLID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CLID] DEFAULT (N''),
[_CX_PROBLOAN_5] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBLOAN_5] DEFAULT (N''),
[_CX_PROBLOANDESC_5] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBLOANDESC_5] DEFAULT (N''),
[_CX_UWDOC_5] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWDOC_5] DEFAULT (N''),
[_CX_UWADDR_5] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWADDR_5] DEFAULT (N''),
[_CX_UWPROP_9] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWPROP_9] DEFAULT (N''),
[_CX_UWAMORT_6] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWAMORT_6] DEFAULT (N''),
[_CX_UWPURP_5] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWPURP_5] DEFAULT (N''),
[_CX_UWCITY_5] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWCITY_5] DEFAULT (N''),
[_CX_UWLIEN_6] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWLIEN_6] DEFAULT (N''),
[_CX_UWZIP_5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWZIP_5] DEFAULT (N''),
[_CX_UWSTATE_5] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWSTATE_5] DEFAULT (N''),
[_CX_UWLNTYPE_5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWLNTYPE_5] DEFAULT (N''),
[_CX_UWOCC_6] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWOCC_6] DEFAULT (N''),
[_CX_COVERCOND2_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND2_11] DEFAULT (N''),
[_CX_COVERCOND3_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND3_11] DEFAULT (N''),
[_CX_COVERCOND1_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND1_11] DEFAULT (N''),
[Log_MS_LastCompleted] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLog_MS_LastCompleted] DEFAULT (N''),
[_CX_COVERCOND10_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND10_11] DEFAULT (N''),
[_CX_COVERCOND8_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND8_11] DEFAULT (N''),
[_CX_COVERCOND9_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND9_11] DEFAULT (N''),
[_CX_COVERCOND6_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND6_11] DEFAULT (N''),
[_CX_COVERCOND7_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND7_11] DEFAULT (N''),
[_CX_COVERCOND4_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND4_11] DEFAULT (N''),
[_CX_COVERCOND5_11] [varchar] (125) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_COVERCOND5_11] DEFAULT (N''),
[_1407] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1407] DEFAULT (N''),
[_88] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_88] DEFAULT (N''),
[_87] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_87] DEFAULT (N''),
[_CX_UWPROG_11] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWPROG_11] DEFAULT (N''),
[_315] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_315] DEFAULT (N''),
[_326] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_326] DEFAULT (N''),
[_SYS_X167] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X167] DEFAULT (N''),
[_SYS_X142] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X142] DEFAULT (N''),
[_SYS_X293] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X293] DEFAULT (N''),
[_1956] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1956] DEFAULT (N''),
[_321] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_321] DEFAULT (N''),
[_SYS_X232] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X232] DEFAULT (N''),
[_SYS_X298] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X298] DEFAULT (N''),
[_SYS_X234] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X234] DEFAULT (N''),
[_SYS_X235] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X235] DEFAULT (N''),
[_SYS_X162] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X162] DEFAULT (N''),
[_SYS_X163] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X163] DEFAULT (N''),
[_SYS_X164] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X164] DEFAULT (N''),
[_SYS_X165] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X165] DEFAULT (N''),
[_323] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_323] DEFAULT (N''),
[_SYS_X231] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X231] DEFAULT (N''),
[_324] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_324] DEFAULT (N''),
[_SYS_X147] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X147] DEFAULT (N''),
[_1538] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1538] DEFAULT (N''),
[_189] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_189] DEFAULT (N''),
[_1529] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1529] DEFAULT (N''),
[_1528] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1528] DEFAULT (N''),
[_CX_UWVALUEBOX_11] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWVALUEBOX_11] DEFAULT (N''),
[_188] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_188] DEFAULT (N''),
[_CX_UWESCROW_11] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWESCROW_11] DEFAULT (N''),
[LOCKRATE_1130] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_1130] DEFAULT (N''),
[_1525] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1525] DEFAULT (N''),
[_1524] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1524] DEFAULT (N''),
[_1527] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1527] DEFAULT (N''),
[_1526] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1526] DEFAULT (N''),
[_1530] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1530] DEFAULT (N''),
[_1533] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1533] DEFAULT (N''),
[_1532] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1532] DEFAULT (N''),
[_1535] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1535] DEFAULT (N''),
[_1534] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1534] DEFAULT (N''),
[_1537] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1537] DEFAULT (N''),
[_1536] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1536] DEFAULT (N''),
[_CX_PURMISC3_12] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PURMISC3_12] DEFAULT (N''),
[_CX_LOCK_12] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_LOCK_12] DEFAULT (N''),
[_CX_STRINGFIELD1_12] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_STRINGFIELD1_12] DEFAULT (N''),
[_CX_NEEDCOMMIT_12] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_NEEDCOMMIT_12] DEFAULT (N''),
[_CX_FLOATLOAN_12] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FLOATLOAN_12] DEFAULT (N''),
[_CX_ACTIVELOAN_12] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ACTIVELOAN_12] DEFAULT (N''),
[_1544] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1544] DEFAULT (N''),
[_1556] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1556] DEFAULT (N''),
[_1543] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1543] DEFAULT (N''),
[_1545] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1545] DEFAULT (N''),
[_934] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_934] DEFAULT (N''),
[_CX_DOCTRANSLATE_12] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_DOCTRANSLATE_12] DEFAULT (N''),
[_2275] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2275] DEFAULT (N''),
[_FE0217] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0217] DEFAULT (N''),
[_CX_UWUNIT_12] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWUNIT_12] DEFAULT (N''),
[_FE0115] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0115] DEFAULT (N''),
[_FE0215] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FE0215] DEFAULT (N''),
[_CX_CREDITCARDALPHA_12] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CREDITCARDALPHA_12] DEFAULT (N''),
[_1066] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1066] DEFAULT (N''),
[_VEND_X296] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X296] DEFAULT (N''),
[_VEND_X297] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X297] DEFAULT (N''),
[_VEND_X294] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X294] DEFAULT (N''),
[_VEND_X302] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X302] DEFAULT (N''),
[_VEND_X295] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X295] DEFAULT (N''),
[_VEND_X303] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X303] DEFAULT (N''),
[_VEND_X306] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X306] DEFAULT (N''),
[_2986] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2986] DEFAULT (N''),
[_MORNET_X70] [varchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_MORNET_X70] DEFAULT (N''),
[_CX_PROBLOANCLSDESC_14] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBLOANCLSDESC_14] DEFAULT (N''),
[_CX_PROBLOANSUB_14] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBLOANSUB_14] DEFAULT (N''),
[_CX_PROBLOANCLS_14] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBLOANCLS_14] DEFAULT (N''),
[_CX_PROBLOANSUBDESC_14] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_PROBLOANSUBDESC_14] DEFAULT (N''),
[_SYS_X243] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X243] DEFAULT (N''),
[_SYS_X244] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X244] DEFAULT (N''),
[_352] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_352] DEFAULT (N''),
[_651] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_651] DEFAULT (N''),
[_SYS_X380] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X380] DEFAULT (N''),
[_SYS_X249] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X249] DEFAULT (N''),
[_SYS_X382] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X382] DEFAULT (N''),
[_SYS_X383] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X383] DEFAULT (N''),
[_SYS_X250] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X250] DEFAULT (N''),
[_SYS_X295] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X295] DEFAULT (N''),
[_SYS_X216] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X216] DEFAULT (N''),
[_SYS_X301] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X301] DEFAULT (N''),
[_SYS_X302] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X302] DEFAULT (N''),
[_SYS_X63] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X63] DEFAULT (N''),
[_SYS_X62] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X62] DEFAULT (N''),
[_SYS_X227] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X227] DEFAULT (N''),
[_SYS_X64] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X64] DEFAULT (N''),
[_40] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_40] DEFAULT (N''),
[_SYS_X300] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X300] DEFAULT (N''),
[_43] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_43] DEFAULT (N''),
[_SYS_X112] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X112] DEFAULT (N''),
[_650] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_650] DEFAULT (N''),
[_SYS_X114] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X114] DEFAULT (N''),
[_SYS_X115] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X115] DEFAULT (N''),
[_SYS_X61] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X61] DEFAULT (N''),
[_SYS_X225] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X225] DEFAULT (N''),
[_SYS_X226] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X226] DEFAULT (N''),
[_SYS_X248] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X248] DEFAULT (N''),
[_SYS_X228] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X228] DEFAULT (N''),
[_SYS_X229] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X229] DEFAULT (N''),
[_SYS_X230] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X230] DEFAULT (N''),
[_SYS_X190] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X190] DEFAULT (N''),
[_SYS_X191] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X191] DEFAULT (N''),
[_SYS_X192] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X192] DEFAULT (N''),
[_SYS_X193] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X193] DEFAULT (N''),
[_SYS_X384] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X384] DEFAULT (N''),
[_SYS_X385] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X385] DEFAULT (N''),
[_SYS_X386] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X386] DEFAULT (N''),
[_SYS_X387] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X387] DEFAULT (N''),
[_SYS_X291] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X291] DEFAULT (N''),
[_SYS_X292] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X292] DEFAULT (N''),
[_SYS_X294] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X294] DEFAULT (N''),
[_SYS_X296] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X296] DEFAULT (N''),
[_SYS_X297] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X297] DEFAULT (N''),
[_SYS_X299] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X299] DEFAULT (N''),
[_SYS_X375] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X375] DEFAULT (N''),
[_SYS_X376] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X376] DEFAULT (N''),
[_SYS_X378] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X378] DEFAULT (N''),
[_SYS_X379] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X379] DEFAULT (N''),
[_SYS_X113] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X113] DEFAULT (N''),
[_SYS_X381] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X381] DEFAULT (N''),
[_SYS_X215] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X215] DEFAULT (N''),
[_SYS_X374] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X374] DEFAULT (N''),
[_SYS_X377] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYS_X377] DEFAULT (N''),
[_1601] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1601] DEFAULT (N''),
[_VEND_X154] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X154] DEFAULT (N''),
[_VEND_X119] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X119] DEFAULT (N''),
[_VEND_X131] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X131] DEFAULT (N''),
[_1039] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1039] DEFAULT (N''),
[_VEND_X122] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X122] DEFAULT (N''),
[_VEND_X402] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X402] DEFAULT (N''),
[_VEND_X130] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X130] DEFAULT (N''),
[_VEND_X120] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X120] DEFAULT (N''),
[_VEND_X400] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X400] DEFAULT (N''),
[_VEND_X143] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X143] DEFAULT (N''),
[_VEND_X263] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_VEND_X263] DEFAULT (N''),
[_RE88395_X322] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_RE88395_X322] DEFAULT (N''),
[_2371] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_2371] DEFAULT (N''),
[_CX_APPRORDFMCOMMENTS_4] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_APPRORDFMCOMMENTS_4] DEFAULT (N''),
[_CX_CLSFLODCERT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSFLODCERT] DEFAULT (N''),
[_CX_CLSMATCH] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSMATCH] DEFAULT (N''),
[_CX_WHWELLS] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_WHWELLS] DEFAULT (N''),
[LOCKRATE_2867] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_2867] DEFAULT (N''),
[LOCKRATE_2950] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_2950] DEFAULT (N''),
[_CX_ATRISK] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_ATRISK] DEFAULT (N''),
[_CX_CLSAPPR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSAPPR] DEFAULT (N''),
[_CX_CLSMISC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSMISC] DEFAULT (N''),
[_CX_CLSVOE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSVOE] DEFAULT (N''),
[_CX_JUMBO] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_JUMBO] DEFAULT (N''),
[_CX_CLSINSUR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSINSUR] DEFAULT (N''),
[_CX_CLSADDMISMATCH] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSADDMISMATCH] DEFAULT (N''),
[LOCKRATE_2448] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_2448] DEFAULT (N''),
[_CX_WHCHASE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_WHCHASE] DEFAULT (N''),
[_CX_WHASSOCIATED] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_WHASSOCIATED] DEFAULT (N''),
[_CX_CLSMDIAISS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSMDIAISS] DEFAULT (N''),
[LOCKRATE_2088] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE_2088] DEFAULT (N''),
[_20] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_20] DEFAULT (N''),
[_CX_WHUSBANK] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_WHUSBANK] DEFAULT (N''),
[_CX_CLSMISSDOC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSMISSDOC] DEFAULT (N''),
[_CX_CLSMISCTDDATE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CLSMISCTDDATE] DEFAULT (N''),
[LOCKRATE3_2951] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2951] DEFAULT (N''),
[LOCKRATE3_2961] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2961] DEFAULT (N''),
[LOCKRATE3_2952] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2952] DEFAULT (N''),
[LOCKRATE3_2962] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2962] DEFAULT (N''),
[LOCKRATE3_2950] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2950] DEFAULT (N''),
[LOCKRATE3_2958] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2958] DEFAULT (N''),
[LOCKRATE3_2867] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2867] DEFAULT (N''),
[LOCKRATE3_19] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_19] DEFAULT (N''),
[LOCKRATE3_3041] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_3041] DEFAULT (N''),
[LOCKRATE3_1811] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_1811] DEFAULT (N''),
[LOCKRATE3_2866] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2866] DEFAULT (N''),
[LOCKRATE3_2278] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DFLOCKRATE3_2278] DEFAULT (N''),
[_CX_CANCELLOAN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CANCELLOAN] DEFAULT (N''),
[_CX_FINALTITLE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FINALTITLE] DEFAULT (N''),
[_CX_FINALTITREF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_FINALTITREF] DEFAULT (N''),
[_319] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_319] DEFAULT (N''),
[_617] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_617] DEFAULT (N''),
[_CX_CCCHARGEDESC] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CCCHARGEDESC] DEFAULT (N''),
[_1450_P2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_1450_P2] DEFAULT (N''),
[_NEWHUD2_X2801] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2801] DEFAULT (N''),
[_NEWHUD2_X1613] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X1613] DEFAULT (N''),
[_NEWHUD2_X2900] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NEWHUD2_X2900] DEFAULT (N'')
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[ti_LOANXDB_S_04_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_04]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF NOT EXISTS( SELECT 1 FROM emdbuser.LoanSummary ls JOIN inserted i ON i.XRefID = ls.XRefID)
	BEGIN

		INSERT INTO emdbuser.LoanSummary([Guid]
										,[LoanNumber]
										,[LoanFolder] 
										,[LoanName]
										,[Status]
										,[loanStatus]
										,[RateLockStatus]
										,[RateIsLocked]
										,[Broker]
										,XRefID
										,LastModified
										,BorrowerRace
										,CoBorrowerRace
										,BorrowerEthnicity
										,CoBorrowerEthnicity
										,LoanCloserId
										,Investor
										,AppraisalVendor)
		SELECT NEWID()
			  ,''
			  ,_LOANFOLDER
			  ,NEWID()
			  ,'A'
			  ,''
			  ,''
			  ,''
			  ,''
			  ,XRefID
			  ,GETDATE()
			  ,CASE WHEN _1524 = 'Y' THEN 'American Indian or Alaska Native; ' ELSE '' END
			   + CASE WHEN _1525 = 'Y' THEN 'Asian; ' ELSE '' END
			   + CASE WHEN _1526 = 'Y' THEN 'Black or African American; ' ELSE '' END
			   + CASE WHEN _1527 = 'Y' THEN 'Native Hawaiian or Other Pacific Islander;  ' ELSE '' END
			   + CASE WHEN _1528 = 'Y' THEN 'White; ' ELSE '' END
			   + CASE WHEN _1529 = 'Y' THEN 'Information not provided; ' ELSE '' END
			   + CASE WHEN _1530 = 'Y' THEN 'Not Applicable; ' ELSE '' END
			  ,CASE WHEN _1532 = 'Y' THEN 'American Indian or Alaska Native; ' ELSE '' END
			   + CASE WHEN _1533 = 'Y' THEN 'Asian; ' ELSE '' END
			   + CASE WHEN _1534 = 'Y' THEN 'Black or African American; ' ELSE '' END
			   + CASE WHEN _1535 = 'Y' THEN 'Native Hawaiian or Other Pacific Islander;  ' ELSE '' END
			   + CASE WHEN _1536 = 'Y' THEN 'White; ' ELSE '' END
			   + CASE WHEN _1537 = 'Y' THEN 'Information not provided; ' ELSE '' END
			   + CASE WHEN _1538 = 'Y' THEN 'Not Applicable' ELSE '' END
			  ,_1523
			  ,_1531
			  ,_CLID
			  ,_VEND_X263
			  ,_617
		FROM inserted i
	END
	ELSE

		UPDATE ls
		SET  LoanFolder = i._LOANFOLDER
			,BorrowerRace = CASE WHEN _1524 = 'Y' THEN 'American Indian or Alaska Native; ' ELSE '' END
						    + CASE WHEN _1525 = 'Y' THEN 'Asian; ' ELSE '' END
						    + CASE WHEN _1526 = 'Y' THEN 'Black or African American; ' ELSE '' END
						    + CASE WHEN _1527 = 'Y' THEN 'Native Hawaiian or Other Pacific Islander;  ' ELSE '' END
						    + CASE WHEN _1528 = 'Y' THEN 'White; ' ELSE '' END
						    + CASE WHEN _1529 = 'Y' THEN 'Information not provided; ' ELSE '' END
						    + CASE WHEN _1530 = 'Y' THEN 'Not Applicable' ELSE '' END
			,CoBorrowerRace = CASE WHEN _1532 = 'Y' THEN 'American Indian or Alaska Native; ' ELSE '' END
							  + CASE WHEN _1533 = 'Y' THEN 'Asian; ' ELSE '' END
							  + CASE WHEN _1534 = 'Y' THEN 'Black or African American; ' ELSE '' END
							  + CASE WHEN _1535 = 'Y' THEN 'Native Hawaiian or Other Pacific Islander;  ' ELSE '' END
							  + CASE WHEN _1536 = 'Y' THEN 'White; ' ELSE '' END
							  + CASE WHEN _1537 = 'Y' THEN 'Information not provided; ' ELSE '' END
							  + CASE WHEN _1538 = 'Y' THEN 'Not Applicable' ELSE '' END
			,BorrowerEthnicity = i._1523
			,CoBorrowerEthnicity = i._1531
			,LoanCloserId = i._CLID
			,Investor = i._VEND_X263
			,AppraisalVendor = i._617
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [emdbuser].[tu_LOANXDB_S_04_Forklift_LoanSummary]
   ON  [emdbuser].[LOANXDB_S_04]
   AFTER UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	IF (UPDATE(_LOANFOLDER) OR UPDATE(XRefID) OR UPDATE(Log_MS_LastCompleted) OR UPDATE(_1535) OR UPDATE(_1523) OR UPDATE(_1531) OR UPDATE(_CLID) OR UPDATE(_VEND_X263) OR UPDATE(_1524) 
		OR UPDATE(_617)	OR UPDATE(_1525) OR UPDATE(_1526) OR UPDATE(_1527) OR UPDATE(_1528) OR UPDATE(_1529) OR UPDATE(_1530) OR UPDATE(_1532) OR UPDATE(_1533) OR UPDATE(_1534) 
		OR UPDATE(_1535) OR UPDATE(_1536) OR UPDATE(_1537) OR UPDATE(_1538))
		
		UPDATE ls
		SET  LoanFolder = i._LOANFOLDER
			,BorrowerRace = CASE WHEN _1524 = 'Y' THEN 'American Indian or Alaska Native; ' ELSE '' END + 
						    CASE WHEN _1525 = 'Y' THEN 'Asian; ' ELSE '' END +
						    CASE WHEN _1526 = 'Y' THEN 'Black or African American; ' ELSE '' END +
						    CASE WHEN _1527 = 'Y' THEN 'Native Hawaiian or Other Pacific Islander;  ' ELSE '' END +
						    CASE WHEN _1528 = 'Y' THEN 'White; ' ELSE '' END +
						    CASE WHEN _1529 = 'Y' THEN 'Information not provided; ' ELSE '' END +
						    CASE WHEN _1530 = 'Y' THEN 'Not Applicable' ELSE '' END
			,CoBorrowerRace = CASE WHEN _1532 = 'Y' THEN 'American Indian or Alaska Native; ' ELSE '' END +
							  CASE WHEN _1533 = 'Y' THEN 'Asian; ' ELSE '' END +
							  CASE WHEN _1534 = 'Y' THEN 'Black or African American; ' ELSE '' END +
							  CASE WHEN _1535 = 'Y' THEN 'Native Hawaiian or Other Pacific Islander;  ' ELSE '' END +
							  CASE WHEN _1536 = 'Y' THEN 'White; ' ELSE '' END +
							  CASE WHEN _1537 = 'Y' THEN 'Information not provided; ' ELSE '' END +
							  CASE WHEN _1538 = 'Y' THEN 'Not Applicable' ELSE '' END
			,BorrowerEthnicity = i._1523
			,CoBorrowerEthnicity = i._1531
			,LoanCloserId = i._CLID
			,Investor = i._VEND_X263
			,AppraisalVendor = i._617
			,LastModified = GETDATE()
		FROM emdbuser.LoanSummary ls
		JOIN inserted i ON i.XRefID = ls.XRefID

	



END
GO
ALTER TABLE [emdbuser].[LOANXDB_S_04] ADD CONSTRAINT [PK_LOANXDB_S_04_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_04__1523] ON [emdbuser].[LOANXDB_S_04] ([_1523]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_04_1531] ON [emdbuser].[LOANXDB_S_04] ([_1531]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_04_LoanService_04] ON [emdbuser].[LOANXDB_S_04] ([_LOANFOLDER], [XrefId]) INCLUDE ([_FE0115], [_VEND_X152], [_VEND_X263]) WITH (FILLFACTOR=100, PAD_INDEX=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_GRI_LOANXDB_S_04__VEND_X152__LOANFOLDER_Includes] ON [emdbuser].[LOANXDB_S_04] ([_VEND_X152], [_LOANFOLDER]) INCLUDE ([_CX_ACTIVELOAN_12], [_VEND_X139], [_VEND_X141], [_VEND_X263], [Log_MS_DateTime_AssignedtoUW], [XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
