CREATE TABLE [emdbuser].[LOANXDB_S_23]
(
[XrefId] [int] NOT NULL,
[_CX_UW_LS_INCOME] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UW_LS_INCOME] DEFAULT (N''),
[_CX_UW_LS_OVERALL_RISK] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UW_LS_OVERALL_RISK] DEFAULT (N''),
[_CX_UWXRA_8] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXRA_8] DEFAULT (N''),
[_CX_UWXRA_11] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_UWXRA_11] DEFAULT (N''),
[_CX_GRANT] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_GRANT] DEFAULT (N''),
[_CX_POAREVIEWER] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_POAREVIEWER] DEFAULT (N''),
[_CX_CUSTLOTYPE] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CX_CUSTLOTYPE] DEFAULT (N'')
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_S_23] ADD CONSTRAINT [PK_LOANXDB_S_23_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
