CREATE TABLE [emdbuser].[LOANXDB_S_28]
(
[XrefId] [int] NOT NULL,
[_CX_ERRORS_WAIVED_COMMENTS] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__CX_ERRORS_WAIVED_COMMENTS] DEFAULT (''),
[_CX_RUSH_WAIVED_COMMENTS] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__CX_RUSH_WAIVED_COMMENTS] DEFAULT (''),
[_CX_UIS_COMMENTS] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__CX_UIS_COMMENTS] DEFAULT (''),
[_CX_TITLECO_NAME_WAREHOUSE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__CX_TITLECO_NAME_WAREHOUSE] DEFAULT (''),
[_3778] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__3778] DEFAULT (''),
[_SERVICE_X110] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__SERVICE_X110] DEFAULT (''),
[_CX_CDDESKSUB] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__CX_CDDESKSUB] DEFAULT (''),
[_CX_CDSENT] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__CX_CDSENT] DEFAULT (''),
[_CX_CDDESKREVIEWER] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_LOANXDB_S_28__CX_CDDESKREVIEWER] DEFAULT (''),
[_LOANNAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [emdbuser].[LOANXDB_S_28] ADD CONSTRAINT [PK_LOANXDB_S_28_XrefId] PRIMARY KEY CLUSTERED  ([XrefId]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
