CREATE TABLE [dbo].[tally2]
(
[n] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tally2] ADD CONSTRAINT [pk_cl_tally2] PRIMARY KEY CLUSTERED  ([n]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tally2] ADD CONSTRAINT [uq_dbo_tally2] UNIQUE NONCLUSTERED  ([n]) ON [PRIMARY]
GO
