SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[numbers_demo] (@maxN bigint)
RETURNS TABLE WITH SCHEMABINDING AS RETURN
WITH 
E1(N) AS (SELECT 1 FROM (VALUES (1),(1),(1),(1),(1),(1),(1),(1),(1),(1)) X(X)),
E3(N) AS (SELECT 1 FROM E1 a CROSS JOIN E1 b CROSS JOIN E1 c) -- 10^3 = 1,000
SELECT TOP (@maxN) N = ROW_NUMBER() OVER (ORDER BY (SELECT NULL))
FROM E3 a CROSS JOIN E3 b CROSS JOIN E3 c -- 1,000^3 = 1,000,000,000;
GO
