SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[triangleNumberAB] (@N INT)
RETURNS TABLE WITH SCHEMABINDING AS RETURN
SELECT tn.n, tn.triangled FROM dbo.triangleNumber tn WHERE @N = N;
GO
