SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[getshortstring8k](@s1 varchar(8000), @s2 varchar(8000))
RETURNS TABLE WITH SCHEMABINDING AS RETURN 
SELECT
  s1 = CASE WHEN DATALENGTH(@s1) < DATALENGTH(@s2) THEN @s1 ELSE @s2 END,
  s2 = CASE WHEN DATALENGTH(@s1) < DATALENGTH(@s2) THEN @s2 ELSE @s1 END;
GO
