SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [samd].[bernieEL] (@string1 VARCHAR(8000), @string2 VARCHAR(8000))
RETURNS TABLE WITH SCHEMABINDING AS RETURN
SELECT BD = SIGN(CHARINDEX(SUBSTRING(a.s1,0,a.l1),a.s2))|
            SIGN(CHARINDEX(SUBSTRING(a.s1,2,a.l1),a.s2))
FROM (VALUES(@string1,@string2,DATALENGTH(@string1))) a(s1,s2,l1);
GO
