SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [samd].[bernieDistance8K_V2](@string1 VARCHAR(8000), @string2 VARCHAR(8000))
RETURNS TABLE WITH SCHEMABINDING AS RETURN
SELECT ABS(DATALENGTH(@string1)-DATALENGTH(@string2)) * 
       SIGN(CHARINDEX(@string1,@string2)|CHARINDEX(@string2,@string1)) AS BD
GO
