CREATE TABLE [Inst].[LongRunningQuery]
(
[ServerName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InstanceName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextData] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BinaryData] [image] NULL,
[DatabaseID] [int] NULL,
[TransactionID] [bigint] NULL,
[LineNumber] [int] NULL,
[NTUserName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NTDomainName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HostName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientProcessID] [int] NULL,
[ApplicationName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoginName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPID] [int] NULL,
[Duration] [bigint] NULL,
[StartTime] [datetime] NULL,
[EndTime] [datetime] NULL,
[Reads] [bigint] NULL,
[Writes] [bigint] NULL,
[CPU] [int] NULL,
[Permissions] [bigint] NULL,
[Severity] [int] NULL,
[EventSubClass] [int] NULL,
[ObjectID] [int] NULL,
[Success] [int] NULL,
[IndexID] [int] NULL,
[IntegerData] [int] NULL,
[TServerName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventClass] [int] NULL,
[ObjectType] [int] NULL,
[NestLevel] [int] NULL,
[State] [int] NULL,
[Error] [int] NULL,
[Mode] [int] NULL,
[Handle] [int] NULL,
[ObjectName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatabaseName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoleName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TargetUserName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBUserName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoginSid] [image] NULL,
[TargetLoginName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TargetLoginSid] [image] NULL,
[ColumnPermissions] [int] NULL,
[LinkedServerName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MethodName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowCounts] [bigint] NULL,
[RequestID] [int] NULL,
[XactSequence] [bigint] NULL,
[EventSequence] [bigint] NULL,
[BigintData1] [bigint] NULL,
[BigintData2] [bigint] NULL,
[GUID] [uniqueidentifier] NULL,
[IntegerData2] [int] NULL,
[ObjectID2] [bigint] NULL,
[Type] [int] NULL,
[OwnerID] [int] NULL,
[ParentName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSystem] [int] NULL,
[Offset] [int] NULL,
[SourceDatabaseID] [int] NULL,
[SqlHandle] [image] NULL,
[SessionLoginName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanHandle] [image] NULL,
[GroupID] [int] NULL,
[RunDate] [datetime] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nc_inst_longRunningQuery] ON [Inst].[LongRunningQuery] ([LoginName], [StartTime]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nc_Inst_LongRunningQuery__startTime] ON [Inst].[LongRunningQuery] ([StartTime]) INCLUDE ([CPU], [EndTime], [LoginName], [Reads], [RowCounts], [Writes]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [nc_Inst_LongRunningQuery__ServerName] ON [Inst].[LongRunningQuery] ([StartTime], [ServerName]) ON [PRIMARY]
GO
