IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\NEJohnson')
CREATE LOGIN [GRCORP\NEJohnson] FROM WINDOWS
GO
CREATE USER [GRCORP\NEJohnson] FOR LOGIN [GRCORP\NEJohnson]
GO
