IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\Online SQL SEC')
CREATE LOGIN [GRCORP\Online SQL SEC] FROM WINDOWS
GO
CREATE USER [GRCORP\Online SQL SEC] FOR LOGIN [GRCORP\Online SQL SEC]
GO
GRANT SHOWPLAN TO [GRCORP\Online SQL SEC]
GRANT VIEW DEFINITION TO [GRCORP\Online SQL SEC]
