IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\ORG_PX_API')
CREATE LOGIN [GRCORP\ORG_PX_API] FROM WINDOWS
GO
CREATE USER [GRCORP\ORG_PX_API] FOR LOGIN [GRCORP\ORG_PX_API]
GO
