IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\Marketing SQL SEC')
CREATE LOGIN [GRCORP\Marketing SQL SEC] FROM WINDOWS
GO
CREATE USER [GRCORP\Marketing SQL SEC] FOR LOGIN [GRCORP\Marketing SQL SEC]
GO
