IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\ORG_TSLoan_Prod')
CREATE LOGIN [GRCORP\ORG_TSLoan_Prod] FROM WINDOWS
GO
CREATE USER [GRCORP\ORG_TSLoan_Prod] FOR LOGIN [GRCORP\ORG_TSLoan_Prod]
GO
