IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\ORG_Tableau')
CREATE LOGIN [GRCORP\ORG_Tableau] FROM WINDOWS
GO
CREATE USER [GRCORP\ORG_Tableau] FOR LOGIN [GRCORP\ORG_Tableau]
GO
