IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\ORG_OAP_Dev')
CREATE LOGIN [GRCORP\ORG_OAP_Dev] FROM WINDOWS
GO
CREATE USER [GRCORP\ORG_OAP_Dev] FOR LOGIN [GRCORP\ORG_OAP_Dev]
GO
