IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\ORG_Person_Dev')
CREATE LOGIN [GRCORP\ORG_Person_Dev] FROM WINDOWS
GO
CREATE USER [GRCORP\ORG_Person_Dev] FOR LOGIN [GRCORP\ORG_Person_Dev]
GO
