IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\Development SQL SEC')
CREATE LOGIN [GRCORP\Development SQL SEC] FROM WINDOWS
GO
CREATE USER [GRCORP\Development SQL SEC] FOR LOGIN [GRCORP\Development SQL SEC]
GO
GRANT SHOWPLAN TO [GRCORP\Development SQL SEC]
GRANT VIEW DEFINITION TO [GRCORP\Development SQL SEC]
