IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\ORG_PX_API_DEV')
CREATE LOGIN [GRCORP\ORG_PX_API_DEV] FROM WINDOWS
GO
CREATE USER [GRCORP\ORG_PX_API_DEV] FOR LOGIN [GRCORP\ORG_PX_API_DEV] WITH DEFAULT_SCHEMA=[emdbuser]
GO
