IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\MMcLain')
CREATE LOGIN [GRCORP\MMcLain] FROM WINDOWS
GO
CREATE USER [GRCORP\MMcLain] FOR LOGIN [GRCORP\MMcLain] WITH DEFAULT_SCHEMA=[emdbuser]
GO
