IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\BusOps SQL SEC')
CREATE LOGIN [GRCORP\BusOps SQL SEC] FROM WINDOWS
GO
CREATE USER [GRCORP\BusOps SQL SEC] FOR LOGIN [GRCORP\BusOps SQL SEC]
GO
