IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GRCORP\ORG_SSIS_D')
CREATE LOGIN [GRCORP\ORG_SSIS_D] FROM WINDOWS
GO
CREATE USER [GRCORP\ORG_SSIS_D] FOR LOGIN [GRCORP\ORG_SSIS_D]
GO
