CREATE TABLE [tSQLt].[Private_NewTestClassList]
(
[ClassName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [tSQLt].[Private_NewTestClassList] ADD CONSTRAINT [PK__Private___F8BF561A0519C6AF] PRIMARY KEY CLUSTERED  ([ClassName]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
